### ISSUE TITLE
Apache module needs to be updated to fully work with Apache 2.4.

### ISSUE THREAD

**Issue by Usalabs** [webmin/webmin#1700]
The Apache server module needs to be updated to work properly with Apache 2.4, because there's new directives that are not being set using the webmin module, and as such, the 'old' directives, are being used instead and are messing around with the new Apache 2.4, and sometimes misconfiguring the server and blocking access.  One of the new directives is 'Require', which is replacing the old:-

Order deny,allow
Deny from all

Directives.

EG
Order deny,allow
Deny from all

Is replaced with:-
Require all denied

The old directives no longer work in Apache 2.4, I suggest reading up on this:-

https://httpd.apache.org/docs/2.4/upgrading.html#access

**Comment by jcameron** [comment]
Have you tried the latest Webmin release? It should fix this specific issue already ..

**Comment by Usalabs** [comment]
> Have you tried the latest Webmin release? It should fix this specific issue already ..

Yes, I have updated to 1.998 and it's still not fixed.

Try this:-

Servers->Apache Webserver, then open the first default virtual host, under 'Per Directory Options' open the folder named /var/www/, then click on 'Access Control' and there you'll see 'Restrict Access' and options for access checking order, and if you select 'Action: Allow' then select 'Allow then deny' and save it, then when you look at the directives, the new Apache 2.4 directive 'Require all .....' is removed and webmin replaces it with:-

order allow,deny
allow from all

Which is not used by Apache 2.4

**Comment by iliajie** [comment]
Yes, you are right -- we are still doing it the old way! It needs to be fixed.

**Comment by swelljoe** [comment]
Surely this has been fixed by now? Can I close this?

**Comment by iliaross** [comment]
Surprisingly we didn't, but now we do! Thanks for bringing this up!
