### ISSUE TITLE
Webmin version 1.999-2 is now available, but you are running version 1.999.

### ISSUE THREAD

**Issue by jmccabe** [webmin/webmin#1713]
Seeing this message in the dashboard but, when I press the "Upgrade Webmin Now" button, I get:

`Failed to upgrade from www.webmin.com : You are already running the latest version of Webmin`

**Comment by jmccabe** [comment]
Also seeing this message when trying to update another install of webmin; I suspect it's related so mentioning it here.

```
WARNING: The following packages cannot be authenticated!
  webmin
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

**Comment by iliajie** [comment]
It seems that `upgrade.cgi` doesn't yet do upgrades for minor versions correctly.

We will fix that.

**Comment by iliajie** [comment]
Reference for further readers - https://sourceforge.net/p/webadmin/discussion/600155/thread/67e368e4a0/?limit=25#1a4c

**Comment by Araflologo** [comment]
If you didn't know you can go to "Webmin Configuration" then "Upgrade Webmin" check the box "Upgrade even if new version is the same or older?" it worked for me or just download the files

**Comment by ccheath** [comment]
_running on Ubuntu 20.04.4_
I downloaded the .deb from sourceforge and installed ... no problems
but the message still says I'm running 1.999 and 1.999-2 is available (and the version is still 1.999 on the status above the msg)
I have restarted webmin with `sudo /etc/webmin/restart` and restarted the server also.... 
what should I do?

**Comment by swelljoe** [comment]
The -2 is a package release version, not the Webmin version. If you have the 1.999-2 package installed, you have that release.

**Comment by swelljoe** [comment]
New releases (-2, -3, etc.) mean there was a change in the package (i.e. postinstall scripts, metadata, etc.) rather than in the software itself.

**Comment by ccheath** [comment]
ok, so just wait for the new version with the `upgrade.cgi` that can do these releases?

**Comment by swelljoe** [comment]
I don't recommend you use upgrade.cgi at all. You have a package manager. Use the danged package manager. We have repos for apt and yum.

**Comment by jcameron** [comment]
The work-around for this issue is to go to Webmin -> Webmin Configuration -> Upgrade Webmin, and check the "Upgrade even if new version is the same or older?" box. Or do as Joe said, and install it using APT or YUM.

**Comment by jcameron** [comment]
The proper fix is here : https://github.com/webmin/webmin/commit/6fc78a2104e5b1b22da02aaeb17f978b5439b2da

**Comment by ccheath** [comment]
I did install 1.999-2 using APT
and by saying "waiting for the new version of upgrade.cgi" I meant waiting for that fix

**Comment by ccheath** [comment]
and the 'work around' didn't remove the message either... still saying that i should upgrade to 1.999-2

**Comment by swelljoe** [comment]
When you use apt or yum, you can/should disable that warning. At that point your package manager is the source of truth for the current available version and installed version. (We do this automatically in the Virtualmin installer.)

**Comment by iliajie** [comment]
> The proper fix is here : [6fc78a2](https://github.com/webmin/webmin/commit/6fc78a2104e5b1b22da02aaeb17f978b5439b2da)

Thanks, Jamie. I have taken a deeper look and found more bugs in regards to upgrades for release versions - https://github.com/webmin/webmin/commit/3dfc71d8c14348ca68512be52869166cbf7525fd.

Also, it's important that when you build Webmin you add to `makedist` command a release version, something like `./makedist.pl 1.999-2`. Doing that will create a `release` file inside of a package. I had it in my build scripts and missed it when was testing yours - sorry about that.

Also, anyone seeing a problem with notification not going away, simply put a text file in Webmin directory (i.e. `/usr/share/webmin` or `/usr/libexec/webmin` or whichever) with a name `release` and put `2` in it. It will represent that Webmin `1.999-2` is installed and will stop notifications from showing.

**Comment by ccheath** [comment]
> Also, anyone seeing a problem with notification not going away, simply put a text file in Webmin directory (i.e. /usr/share/webmin or /usr/libexec/webmin or whichever) with a name release and put 2 in it. It will represent that Webmin 1.999-2 is installed and will stop notifications from showing.
Thank you, this worked!

**Comment by mxdpeep** [comment]
> If you didn't know you can go to "Webmin Configuration" then "Upgrade Webmin" check the box "Upgrade even if new version is the same or older?" it worked for me or just download the files

works fine 👍🍸

**Comment by silen72** [comment]
> If you didn't know you can go to "Webmin Configuration" then "Upgrade Webmin" check the box "Upgrade even if new version is the same or older?" it worked for me or just download the files

This did not work for me while this

> Also, anyone seeing a problem with notification not going away, simply put a text file in Webmin directory (i.e. /usr/share/webmin or /usr/libexec/webmin or whichever) with a name release and put 2 in it. It will represent that Webmin 1.999-2 is installed and will stop notifications from showing.

did.

**Comment by 0xenca** [comment]
Conclusion from this bug is Minus symbol is not for describing versions, must be 1.9999.2

Worked perfectly

> If you didn't know you can go to "Webmin Configuration" then "Upgrade Webmin" check the box "Upgrade even if new version is the same or older?" it worked for me or just download the files

**Comment by tocotronaut** [comment]
Instead of adding Version numbers you could Release Version 2.0 as an Workaround ;)

Any actual Roadmap to 2.0?

**Comment by jcameron** [comment]
Yeah, we will probably release version 2.0 as simpler fix. Functionally it won't be any different from 1.999

**Comment by mxdpeep** [comment]
🤣 😜 😎

Filip Oščádal 🍀📱

**Comment by ccheath** [comment]
Webmin is now saying that usermin is out of date, but the updater says "`Failed to upgrade from www.usermin.com : You are already running the latest version of Usermin`"
I'm running 1.840 and the hover over on the dashboard says that 1.854 is out.
Clicking it takes me to the virtualmin forum with a few users posting the issue I'm seeing... 
anyone here able to help?

**Comment by iliajie** [comment]
The simplest solution is to manually download and install Usermin package, or configure repos that would contain latest Usermin.

We have already made improvements to the code to support minor releases.

**Comment by ccheath** [comment]
how do I manually download the usermin package and configure the repos? 
In the virtualmin forum post linked from the dashboard there was a comment:
> wget latest beta [https://raw.githubusercontent.com/virtualmin/virtualmin-install/845f2f7346d24bab029eff699685401f0af24083/virtualmin-install.sh 5](https://raw.githubusercontent.com/virtualmin/virtualmin-install/845f2f7346d24bab029eff699685401f0af24083/virtualmin-install.sh) and run this command
> sh virtualmin-install.sh --setup

I did that but it didn't seem to make a difference

**Comment by ccheath** [comment]
i get 
`Clearing package caches ..

.. done

Re-fetching available packages ..

.. found 0 possible updates`

**Comment by ccheath** [comment]
doesn't show the virtualmin repo like apt does

> Repository name | Enabled? | Package URL
> -- | -- | --
>   | focal/main/restricted | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-updates/main/restricted | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal/universe | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-updates/universe | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal/multiverse | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-updates/multiverse | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-backports/main/restricted/universe/multiverse | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | disco/partner | No | http://archive.canonical.com/ubuntu
>   | focal-security/main/restricted | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-security/universe | Yes | http://ua.archive.ubuntu.com/ubuntu
>   | focal-security/multiverse | Yes | http://ua.archive.ubuntu.com/ubuntu
> 

> $ sudo apt update
> Hit:1 https://software.virtualmin.com/vm/7/gpl/apt virtualmin InRelease
> Hit:2 http://ua.archive.ubuntu.com/ubuntu focal InRelease
> Hit:3 http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:4 http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease
> Hit:5 http://ua.archive.ubuntu.com/ubuntu focal-security InRelease
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.

**Comment by iliajie** [comment]
Oh, I see, you missed [this](https://github.com/webmin/webmin/issues/1713#issuecomment-1210595465) message above. Running this command will help to make update message go away:

```
miniservconffile=$(find / -wholename "*web*\/miniserv.conf") ; rootdir=$(grep "^root=" "$miniservconffile" | sed -e 's/root=//g') ; echo "2" > "$rootdir/release"
```

**Comment by ccheath** [comment]
i did see that, and the message did go away, but now Usermin is saying that v1.854 is available and I'm on v1.840 ...

**Comment by jcameron** [comment]
Can you apply that Usermin update successfully?

**Comment by ccheath** [comment]
as i posted two days ago here...

> i get
> ```
> Clearing package caches ..
> .. done
> Re-fetching available packages ..
> .. found 0 possible updates
> ```
