### ISSUE TITLE
webmin 2.003 cli connecting... forever

### ISSUE THREAD

**Issue by mxdpeep** [webmin/webmin#1798]
I use Webmin on custom port 2083 through Cloudflare on Hetzner dedicated server behind a HW firewall. Everything works but command line interface shows only "CONNECTING .."

**Comment by iliajie** [comment]
Yes, there is a bug in 2.003 that I missed, which is missing [`websockets-lib-funcs.pl`](https://github.com/webmin/webmin/blob/master/websockets-lib-funcs.pl). We will do our best to release an update as soon as possible. Sorry about that!!

**Comment by JunniH** [comment]
Can this also be related to the webmin web interface not accessible after 2.003 upgrade? Error logs shows the following:

`[27/Nov/2022:15:23:05 +0100] Shutting down
[27/Nov/2022:15:23:13 +0100] miniserv.pl started
[27/Nov/2022:15:23:13 +0100] IPv6 support cannot be enabled without the Socket6 perl module
[27/Nov/2022:15:23:13 +0100] Using MD5 module Digest::MD5
[27/Nov/2022:15:23:13 +0100] Using SHA512 module Crypt::SHA
Can't locate auto/Net/SSLeay/get_servern.al in @INC (@INC contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715
Can't locate auto/Net/SSLeay/get_servern.al in @INC (@INC contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715
Can't locate auto/Net/SSLeay/get_servern.al in @INC (@INC contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715
Can't locate auto/Net/SSLeay/get_servern.al in @INC (@INC contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715`

**Comment by iliajie** [comment]
What is your distro?

**Comment by JunniH** [comment]
CentOS 6 x64

**Comment by iliajie** [comment]
If you go to `Webmin / Tools / Terminal`, what do you get, if you try to install missing Perl modules automatically? Do you have EPEL enabled?

**Comment by JunniH** [comment]
I can't reach the web interface after I clicked the upgrade 2.003 button. I'm getting "This site can’t be reached".

**Comment by iliajie** [comment]
I assume you tried installing `Net-SSLeay` package by running `perl-Net-SSLeay` by running `yum install perl-Net-SSLeay`?

**Comment by iliajie** [comment]
Can I have SSH access to this system?

**Comment by mxdpeep** [comment]
> Yes, there is a bug in 2.003 that I missed, which is missing [`websockets-lib-funcs.pl`](https://github.com/webmin/webmin/blob/master/websockets-lib-funcs.pl). We will do our best to release an update as soon as possible. Sorry about that!!

good to hear that the bug is not on my side of the wire

**Comment by mxdpeep** [comment]
ERROR — PERL EXECUTION FAILED
Undefined subroutine &xterm::allocate_miniserv_websocket called at /usr/share/webmin/xterm/index.cgi line 141.

**Comment by iliajie** [comment]
@JunniH I managed to install CentOS 6. I can see the problem as well. I don't know if we can fix that but I will have a look.

@mxdpeep The fix for this is coming. Meanwhile, you can fix that by putting missing [websockets-lib-funcs.pl](https://github.com/webmin/webmin/blob/master/websockets-lib-funcs.pl) file to Webmin installation dir.

**Comment by JunniH** [comment]
@iliaross : thanks a lot! Executing yum install perl-Net-SSLeay also gives errors...maybe something to do with outdated repository urls

**Comment by iliaross** [comment]
> @iliaross : thanks a lot! Executing yum install perl-Net-SSLeay also gives errors...maybe something to do with outdated repository urls

CentOS 6 is EOL. You would need to setup Vault repos first to make things work/update. Please stop using CentOS 6!

> Can't locate auto/Net/SSLeay/get_servern.al in @INC (@INC contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715

Sorry. It seems that I just need a break, as the error is self-explanatory and must be simple to fix.

**Comment by iliajie** [comment]
> > Can't locate auto/Net/SSLeay/get_servern.al in @inc (@inc contains: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/miniserv.pl line 4715
> 
> Sorry. It seems that I just need a break, as the error is self-explanatory and must be simple to fix.

The fix for this problem is here https://github.com/webmin/webmin/pull/1799

**Comment by mxdpeep** [comment]
> @JunniH I managed to install CentOS 6. I can see the problem as well. I don't know if we can fix that but I will have a look.
> 
> @mxdpeep The fix for this is coming. Meanwhile, you can fix that by putting missing [websockets-lib-funcs.pl](https://github.com/webmin/webmin/blob/master/websockets-lib-funcs.pl) file to Webmin root dir.

404 = bad link :)

**Comment by iliajie** [comment]
Yeah, Jamie just moved the file to `xterm` directory.

**Comment by mxdpeep** [comment]
> Yeah, we just moved the file to `xterm` directory.

I have degraded to http://prdownloads.sourceforge.net/webadmin/webmin_2.000_all.deb and will wait for the official fix 🚬👻

**Comment by lionslair** [comment]
I am getting this 

Error — Perl execution failed

Undefined subroutine &main::authentic called at /usr/local/webmin/authentic-theme/index.cgi line 12.

**Comment by redsector72** [comment]
I still get the same problem on 20.10.
If I go to Tools/terminal I get "Failed loading terminal : Websocket connection error"
This happens only on one of four installation I have

**Comment by ashcoft** [comment]
Either with me, distro CentOS 7.9 Webmin 2.010

**Comment by iliajie** [comment]
If you have Webmin 2.010 installed and you're seeing this issue, it would be interesting to see what gets logged to `/tmp/.webmin/ws-NN.out` file?

**Comment by mxdpeep** [comment]
2.010 works as expected on Ubuntu 22.04.1 🔥

**Comment by iliajie** [comment]
Thanks for the feedback, good to know! Did you install it using Debian package?

**Comment by iliajie** [comment]
> I use Webmin on custom port 2083 through Cloudflare on Hetzner dedicated server behind a HW firewall. Everything works but command line interface shows only "CONNECTING .."

Connecting forever technically is a bug, as it should return the reason why it cannot connect. I will fix it.

**Comment by iliajie** [comment]
Thanks for the heads up! Next release will have a nice and clean connection error message displayed rather than connecting forever.



> If I go to Tools/terminal I get "Failed loading terminal : Websocket connection error"
> This happens only on one of four installation I have

Is this RHEL 8 or Alma/Rocky 8 system?

**Comment by iliajie** [comment]
We will add a fix for the next release to check on more potentially missing dependencies.

> If I go to Tools/terminal I get "Failed loading terminal : Websocket connection error"
> This happens only on one of four installation I have

You need to make sure that you have installed `perl-Digest-SHA` and 'Digest-MD5'.

**Comment by redsector72** [comment]
The ws-xxx.out files are like:

Running shell '/bin/bash -bash' with pid 26785
listening on port 556

Seems the port is always progressing by one for each new attempt
I've installed theme 20.11 and the problem is still there

**Comment by iliajie** [comment]
> Digging I've found:
> Can't locate Net/WebSocket/Server.pm in @inc (you may need to install the Net::WebSocket::Server module)

Can you please try the latest devel package ([RPM](https://ilia.engineer/webmin-2.010-10.noarch.rpm) or [DEB](https://ilia.engineer/webmin_2.010-10_all.deb)). It should fix the issue you're having.

**Comment by redsector72** [comment]
It does not fix, same as previous. I've tried even to manually install the perl package and now states:
"Can't locate ./xterm-lib.pl at /usr/share/webmin/xterm/shellserver.pl line 8."
If I manually fix the line 8, then it pops out:
"Can't locate WebminCore.pm in @INC (you may need to install the WebminCore module)"

I suppose there is something very low level going on

**Comment by redsector72** [comment]
fixing the @inc now pops out:
"WEBMIN_CONFIG not set at usr/share/webmin/web-lib-funcs.pl line 4801."

I hope this helps

**Comment by iliajie** [comment]
I am not sure what is wrong on your side. I assume you messed up while upgrading Webmin files.

Try this new Webmin devel repo. It has all packages you may need in `rpm`, `deb` and `tar` formats.

https://builds.webmin.dev

**Comment by redsector72** [comment]
Installed it and still not working.
If I run manually "/usr/bin/perl /usr/share/webmin/xterm/shellserver.pl 555 root"
Now I get "Can't locate ./xterm-lib.pl at /usr/share/webmin/xterm/shellserver.pl line 8."

**Comment by iliajie** [comment]
> Hi there and thanks for helping me.
> I do:
> wget https://builds.webmin.dev/webmin-latest.deb
> dpkg -i webmin-latest.deb

It is assumed that you are running that command via SSH (in external terminal). Also, it's better to run (after downloading the file) `apt-get install ./webmin-latest.deb` command. Note that `webmin-latest.deb` package has just been updated. Try it further with the super latest build please!

> I would do a backup/clean, but please provide a guide to follow. I have 4 identical raspi and only one is having this issue.

I cannot provide any guide without knowing details about the system. I would suggest to 1. compare installed packages between working and not working berries by running `dpkg -l`, and 2. compare `/etc/webmin/config` and `/etc/webmin/miniserv.conf` files.

**Comment by redsector72** [comment]
I've installed latest as instructions.
I've copied config e ministers.conf from working raspi.
I've checked all installed files

but still not working!

**Comment by iliajie** [comment]
> server=MiniServ/2.010

I thought you said you have upgraded Webmin?

You have SSL disabled (based on your _miniserv_ config posted above), so the problem with non-SSL connections will only be fixed in upcoming Webmin 2.011.

**Comment by ashcoft** [comment]
> 

i got the point, thanks in advance

**Comment by KamMedia** [comment]
I fixed this error on my new server by adding port rule for 550:599 into the firewall settings.
In short, please make sure that you have opened those ports for localhost to connect.

**Comment by KamMedia** [comment]
Anyway, I love the old way to open the config file with `nano /etc/whateverpath/myfile`, because it's open with Webmin build-in text editor directly and it's very easy to do some copy and paste tasks. With the change to the new cli, I have to go into file manager to surf the file to open it. Please consider to add back the old non-interactive cli and let us have a choice. Thanks!

**Comment by KamMedia** [comment]
Thanks for the released of the the new interactive shell, but it's not my cup of tea.

Here are some situations that old shell works better.

With the old shell, we can easily scroll back with mouse wheel to view the long list results returned by command. It really useful when I have to run some commands that will return long list of results 
For example, `lspci`  `ps aux` , `locate` etc.

On top of that, we can use the browser search (Ctrl+f) to search directly for specific keywords  against the long result. However, this function is now no longer available with interactive shell.

Most of my servers are running under Proxmox which already had interactive shell build-in.
However, I still always prefer to use the old webmin shell over Proxmox interactive shell, because it works much smoother on remote server and I really enjoy to use it.

I use the Proxmox interactive shell when I need to run some commands liked `htop` but in most of the case, I still prefer to use the old simple shell provided by webmin because it works better for me.

Best Regards,
Kam

**Comment by iliajie** [comment]
Hi, Kam!

> Anyway, I love the old way to open the config file with nano /etc/whateverpath/myfile, because it's open with Webmin build-in text editor directly and it's very easy to do some copy and paste tasks. With the change to the new cli, I have to go into file manager to surf the file to open it. Please consider to add back the old non-interactive cli and let us have a choice.

This feature is still available, although the commands are `!edit /path/file` or `!view /path/file` but is has to be called from left menu (blue navigation menu) search bar.

> 1. The new interactive shell is not very friendly for copy and paste command, Ctrl+c + Ctrl+v no longer work with it.

At which platform you were trying this? It works for me in MacOS. Note that Xterm can imitate what desktop terminals do, depending on the platform, i.e. in case case of Linux or Windows you may want to use `Ctrl+Shift+C` instead of `Ctrl+C`.



> 2. The new interactive shell is very slow in response. My ping time to the server is around 200ms but the new interactive shell acted like I have to wait for 0.8 seconds for every single character to display.
> 

This works for me on slow connections too. Now sure what we can do here. This issue [been discussed](https://github.com/xtermjs/xterm.js/issues/887) already. We will update to the latest Xterm.js, hopefully it will solve this issue for you.



> 3. With the old simple shell, when I have some really long command to run, I was able to copy and paste that command from my notes to the shell, use the mouse to highlight the parameters that need to be changed and replaced it with ctrl+c & ctrl+v.

You should try adding `Shift` to those keycombos as I mentioned earlier.


> 4. To be honest, I really love the old simple shell, it’s working very smooth on remote server and I have great experience with it. It provides some features and convenience that interactive shell unable to provide.

Also possible -- simply go to `Webmin ⇾ Webmin Users: Edit Webmin User / Available Modules` and disable `Terminal` module in Tools section.

**Comment by KamMedia** [comment]
Hello Iliajie,

Thanks for your help, the step of  `disable Terminal module` for webmin user bring back the simple old shell. 

Best Regards,
Kam

**Comment by jbyerline** [comment]
Hey Y'all, sorry to jump on this thread a little late. I am experiencing a very similar issue. I am running Webmin 2.0.13 on Ubuntu 20.04. I have this instance set up behind an Apache2 reverse proxy. Everything works great except for the terminal. When I access Webmin from it's IP address, the terminal loads perfectly. However, when I access Webmin from the proxy url, (which is https, if that matters), the terminal just says "Connecting..." forever. Any ideas on how to fix this? 

Here is my apache proxy setup: 

```
<VirtualHost *:80>
  ServerName webmin.myurl.com
  Redirect permanent / https://webmin.myurl.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName webmin.myurl.com

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/ca.crt
    SSLCertificateKeyFile /etc/apache2/ssl/ca.key
    SSLCertificateChainFile /etc/apache2/ssl/ca.ca-bundle

    ProxyRequests Off
    ProxyPass / http://10.0.0.100:10000/
    ProxyPassReverse / http://10.0.0.100:10000/
</VirtualHost>
```

**Comment by iliajie** [comment]
You need to proxy WebSockets too. Instead of `ProxyPass` and `ProxyPassReverse` try:

```
<Proxy balancer://webmin>
  BalancerMember http://webmin-server-ip-or-proxy-server-ip:10000/
</Proxy>
ProxyPass /webmin balancer://webmin
```

Also, Terminal configuration page in Webmin 2.013 adds ability to choose `Hostname for WebSocket connections`. Although, this shouldn't be needed.

**Comment by iliajie** [comment]
I think we just need to add reverse proxy configurations (Apache and Nginx) details for Webmin to `webmin.com ⇾ FAQ` .. will do!
