### ISSUE TITLE
File manager : Downloading folder results in error "Error downloading the file because it is outside of allowed directory: /".

### ISSUE THREAD

**Issue by AlexiKhreshnev** [webmin/webmin#1918]
Hello, hope everyone is doing good. I have been using Webmin for around 2-3 weeks now, and have only encountered this issue. 
Here's some info:
-Webmin v2.021
-Ubuntu server 22.04
-Webmin Installation method: Added repository then apt-get install webmin.

Issue:
When attempting to download a folder using file manager ( Right click > Download) i get a toast notification saying that the folder has been archived successfully, then i am instantly redirected to an empty page with the following error message: [{"error":"Error downloading the file because it is outside of allowed directory : /"}]. 
This happens even if i have permission or using root user. I have confirmed that the archives were indeed being created ([home directory]/.tmp). 
I have tried checking my permissions, directories, and folder ownership. This happens even on a clean installation of Webmin v2.021.

Downloading a single file and archiving multiple files or folders then downloading the archive works perfectly fine.
 
In order to dodge this issue i had to uninstall version 2.021 and go back to 2.013. This version did not have this issue at all.

**Comment by jcameron** [comment]
Are you logged in as `root` when you do this, or as a limited user like a Virtualmin domain owner?

**Comment by AlexiKhreshnev** [comment]
Yes, i was logged in as the root user.

**Comment by iliajie** [comment]
> Yes, i was logged in as the root user.

What are the File Manager ACLs set to for the _root_ user? Also, was it a default _root_ user or it's a _root_ capable user?

**Comment by iliajie** [comment]
> Downloading a single file and archiving multiple files or folders then downloading the archive works perfectly fine.

Also, if you go to **Theme Configuration** page and install latest development version of the theme, force reload browser's page and try again -- does it solve your issue? I remember fixing it a while ago.

**Comment by AlexiKhreshnev** [comment]
It was the default root user and its home was set to /root ($HOME) in the ACL.

I did try to change between themes and update them. By default it uses the Authentic Theme. It was version 20.22 and i tried updating to development version 20.30-RC1. Same results.

**Comment by iliajie** [comment]
That is odd. I cannot reproduce this issue with the latest code. By the way, try applying [this patch](https://github.com/webmin/webmin/commit/14a07d49591b4fa37a1cc94d059dda27ddb858e5) and restarting Webmin. Does it fix the problem for you?

If not what is the output of the following command:

```
cat /etc/webmin/filemin/root.acl
```

**Comment by AlexiKhreshnev** [comment]
I have tried applying the patch: Line 330 in the file /usr/share/webmin/web-lib-funcs.pl as the instructions in the link provided. Same result. 

Output of cat /etc/webmin/filemin/root.acl :
work_as_root=1
allowed_paths=$HOME
work_as_user=
max=
allowed_for_edit=application-x-php application-x-ruby application-xml application-xslt+xml application-javascript application-x-shellscript application-x-perl application-x-yaml application-json application-x-x509-ca-cert application-pkix-cert application-sql application-x-sql application-x-asp application-x-aspx application-xhtml+xml

**Comment by iliajie** [comment]
I will have to try to reproduce this issue. It works for me with the latest code. I wonder if Webmin nightly build would fix your issue?

**Comment by AlexiKhreshnev** [comment]
I just tried your suggestion and installed "webmin-latest.deb" from "https://builds.webmin.dev/"
The result is the same. 
So far the only thing I have tried that did not have this issue is webmin 2.013.

**Comment by iliajie** [comment]
Sorry, I really cannot reproduce it with devel build ..

**Comment by AlexiKhreshnev** [comment]
It's alright. I just wanted to share my experience with the issue and any information related to it so others wouldn't suffer from the same problem.
I'd be happy to share any other information or answer any questions that would help.

**Comment by AlexiKhreshnev** [comment]
1. Any directory I try. 
I usually try to download  "/var/www/html". As an example I just created a directory called "testing" (/root/testing) but this also does not work. 

2.
ls -lsa /var/www/
total 12
4 drwxr-xr-x  3 root root 4096 Jun  8 12:15 .
4 drwxr-xr-x 15 root root 4096 Jun  8 12:14 ..
4 drwxr-xr-x  2 root root 4096 Jun  8 12:15 html

lsattr /var/www/
--------------e------- /var/www/html


3. 
[miniserv.txt](https://github.com/webmin/webmin/files/11688262/miniserv.txt)

[config.txt](https://github.com/webmin/webmin/files/11688264/config.txt)





Note: This was done on an ubuntu 22.04 server (LTS) virtual machine.
Hope this helps!

**Comment by david-fox** [comment]
I'm also getting this issue on ubuntu 22.04, authentic 20.21

**Comment by iliajie** [comment]
@AlexiKhreshnev I have tried your configs it still works just fine for me.

@david-fox Have you tried [latest](https://builds.webmin.dev/webmin-latest.deb) devel build? 

Also, what is the content of File Manager config files on your systems, e.g.:

```
cat /etc/webmin/filemin/config
cat /etc/webmin/filemin/prefs.root
```

Also, if the latest devel build doesn't fix your issue could you make a video screencast, with opened browser's console. It would help a lot.

**Comment by AlexiKhreshnev** [comment]
@iliaross 
cat /etc/webmin/filemin/config
Result: allowed_paths=$HOME

cat /etc/webmin/filemin/prefs.root

Result:
[prefsroot.txt](https://github.com/webmin/webmin/files/11702803/prefsroot.txt)

I'll try to record a video shortly.

**Comment by AlexiKhreshnev** [comment]
So i checked the console while attempting the download as i couldn't do a recording.

Here's how it looks before and after the download. (Nothing shows up during the process).

![webmin_screenshot1](https://github.com/webmin/webmin/assets/135302105/c93e5fff-7600-4da9-83ca-0dda8c517384)
![webmin_screenshot2](https://github.com/webmin/webmin/assets/135302105/76d8ca80-138b-49e3-b28e-99d8ac346329)

**Comment by AlexiKhreshnev** [comment]
So i checked the console while attempting the download as i couldn't do a recording.

Here's how it looks before and after the download. (Nothing shows up during the process).

![webmin_screenshot1](https://github.com/webmin/webmin/assets/135302105/c93e5fff-7600-4da9-83ca-0dda8c517384)
![webmin_screenshot2](https://github.com/webmin/webmin/assets/135302105/76d8ca80-138b-49e3-b28e-99d8ac346329)

**Comment by iliajie** [comment]
Thanks for the details! Now I remember the issue more clearly! Although, I was pretty sure that I fixed that in [this](https://github.com/webmin/webmin/commit/14a07d49591b4fa37a1cc94d059dda27ddb858e5) patch!

If you're 100% sure that you have tried the very latest devel build (and force restarted Webmin (not needed but just in case)) .. then most probably you could work around this issue by adding `nohometemp=1` to the Webmin config.

However, I would like to get to the bottom of the problem. I will take a deeper look in to this ..

**Comment by iliajie** [comment]
I have made a new nightly built, if you could install it, then try download as before and attach debug info logged under user home, i.e. `~/.tmp/` or `/tmp/.webmin` .. there should be 2-4 files .. it would help! However, I don't see how this issue can be happening with all latest code .. it makes no sense to me!

**Comment by AlexiKhreshnev** [comment]
Hi, sorry for the late reply. 
I just got the chance to test the new build that you did, but still the same result. 

Checked  "/tmp/.webmin" and only found "webmin-setup.out" inside. Here's it's content:  
[debug info.txt](https://github.com/webmin/webmin/files/11741670/debug.info.txt)


Also checked "~/.tmp" and found 4 files, and here's their output: 
[debug info2.txt](https://github.com/webmin/webmin/files/11741712/debug.info2.txt)

**Comment by AlexiKhreshnev** [comment]
I tried the `nohometemp=1` in  /etc/webmin/config then did `/etc/webmin/restart-by-force-kill` , result is the same. 

Here's the output of the command above: 
```
ps aux | grep miniserv
root      110069  0.3  0.1  42804 30896 ?        Ss   12:52   0:00 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf
root      110435  0.0  0.0   6608  2296 pts/1    S+   12:53   0:00 grep --color=auto miniserv
```

For the installation i did the following:
```
/etc/webmin/uninstall.sh
wget https://builds.webmin.dev/webmin-latest-debug.deb
apt-get install ./webmin-latest-debug.deb
```

**Comment by iliajie** [comment]
I am very confused about what's wrong. It makes no sense!

You are welcome to send a login credentials to us at `security at webmin.com` and one of us will login to your server to see what's wrong.

**Comment by AlexiKhreshnev** [comment]
Thank you greatly for your help and effort @iliaross , am sorry the info i provided wasn't enough to solve the problem.

**Comment by iliajie** [comment]
Why closing this issue? Has it been resolved?

**Comment by iliajie** [comment]
I wonder, what are the permissions set to for `~/.tmp` and `/tmp/.webmin` directories?

**Comment by iliajie** [comment]
Alex, could you edit `sub tempname_dir` line `-w $remote_user_info[7]` and replace it with `-W $remote_user_info[7]`, restart Webmin and give it another shot?

**Comment by iliajie** [comment]
> It was the default root user and its home was set to /root ($HOME) in the ACL.

Also, what is the output of the following command:

```
cat /etc/passwd | grep ^root
```

**Comment by fufu65** [comment]
Hi,
this problem is still present on Ubuntu 22.04 LTS.
All my servers have Ubuntu Server LTS and Webmin 2.102:
Ubuntu 14.04.6 -> ok (1 server)
Ubuntu 16.04.7 -> ok (1 server)
Ubuntu 20.04.6 -> ok (1 server)
Ubuntu 22.04.3 -> KO (10 servers)

Can it be linked to the perl version?
Ubuntu 20.04.6 -> perl 5.30
Ubuntu 22.04.3 -> perl 5.34

Thanks

**Comment by iliaross** [comment]
Reopened, as this was closed by an automated cleanup run.

⚠️ If the issue is resolved, please take a moment to close it to help keep the project organized.
