### ISSUE TITLE
Connection Lost error message

### ISSUE THREAD

**Issue by michele654** [webmin/webmin#2157]
Webmin v 2.111, PHP 8.1.2, Ubuntu 22.04.4

Each day, when I go into webmin, I begin receiving the Connection Lost messages when trying to do most things.  After I run restart-by-force-kill, I can then navigate the webmin panels.  Until the next day, when I receive the Connection Lost message again.

In the error logs I see:
Too many connections (26) from IP yy.yy.yy.yy

**Comment by iliajie** [comment]
Hello,



> Too many connections (26) from IP yy.yy.yy.yy

That's quite a lot of connections. Though you can control it from **Webmin ⇾ Webmin Configuration: Ports and Addresses** page.

**Comment by michele654** [comment]
The issue is, I don't have that many connections.  Something in the latest version of Webmin has started creating connections without my requesting them. 

I'm doing the same workflow I have been doing for years, but this version of Webmin isn't playing well.

**Comment by iliajie** [comment]
If you run `systemctl status webmin` what sub-processes are out there?

**Comment by jcameron** [comment]
That error usually means that something is making too many connections *into* webmin!

**Comment by iliajie** [comment]
Yeah, that's right.  For that I wanted to see if there are any number of outstanding child processes.

Furthermore, looking into `/var/webmin/miniserv.log` will help.

**Comment by michele654** [comment]
**Status  before attempting to go to webmin in a browser
 
systemctl status webmin

* webmin.service - Webmin server daemon
     Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset>
     Active: active (running) since Thu 2024-05-09 23:05:37 BST; 14h ago
    Process: 1346 ExecStart=/usr/share/webmin/miniserv.pl /etc/webmin/miniserv.>
   Main PID: 2472 (miniserv.pl)
      Tasks: 1 (limit: 76942)
     Memory: 179.7M
        CPU: 9.158s
     CGroup: /system.slice/webmin.service
             `-2472 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/min>

May 09 23:05:34 <domain>.com systemd[1]: Starting Webmin server>
May 09 23:05:34 <domain>.com perl[1346]: pam_unix(webmin:auth):>
May 09 23:05:37 <domain> webmin[1346]: Webmin starting
May 09 23:05:37 <domain>.com systemd[1]: Started Webmin server >



**Log entries during my login and attempt at a Terminal

tail -f miniserv.log
(My IP) - - [10/May/2024:13:44:48 +0100] "GET /unauthenticated/css/fonts-roboto.min.css?2110001019999999999 HTTP/1.1" 200 971
(My IP) - - [10/May/2024:13:44:48 +0100] "GET /unauthenticated/css/bundle.min.css?2110001019999999999 HTTP/1.1" 200 186958
(My IP) - - [10/May/2024:13:44:49 +0100] "GET /unauthenticated/fonts/KFOmCnqEu92Fr1Mu4mxK.woff2 HTTP/1.1" 200 15688
(My IP) - - [10/May/2024:13:44:49 +0100] "GET /unauthenticated/fonts/KFOlCnqEu92Fr1MmSU5fBBc4.woff2 HTTP/1.1" 200 15732
(My IP) - - [10/May/2024:13:44:49 +0100] "GET /unauthenticated/fonts/KFOlCnqEu92Fr1MmEU9fBBc4.woff2 HTTP/1.1" 200 15920
(My IP) - - [10/May/2024:13:44:50 +0100] "GET /service-worker.js HTTP/1.1" 401 5210
(My IP) - - [10/May/2024:13:44:50 +0100] "GET /images/favicons/webmin/android-chrome-192x192.png HTTP/1.1" 200 12818
(My IP) - - [10/May/2024:13:44:50 +0100] "GET /images/favicons/webmin/favicon-32x32.png HTTP/1.1" 200 1787
(My IP) - - [10/May/2024:13:44:51 +0100] "GET /service-worker.js HTTP/1.1" 401 5210
(My IP) - - [10/May/2024:13:44:59 +0100] "GET /unauthenticated/fonts/KFOkCnqEu92Fr1Mu51xIIzI.woff2 HTTP/1.1" 200 17304

(Here is where I authenticate and try to go to the Terminal)

(My IP) - - [10/May/2024:13:47:12 +0100] "POST /session_login.cgi HTTP/1.1" 401 4984
(My IP) - - [10/May/2024:13:47:12 +0100] "GET /service-worker.js HTTP/1.1" 401 5210
(My IP) - - [10/May/2024:13:47:12 +0100] "GET /unauthenticated/css/palettes/nightrider.min.css?2110001019999999999 HTTP/1.1" 200 25577
(My IP) - - [10/May/2024:13:47:12 +0100] "GET /unauthenticated/css/fonts-roboto.min.css?2110001019999999999 HTTP/1.1" 200 971
(My IP) - - [10/May/2024:13:47:12 +0100] "GET /service-worker.js HTTP/1.1" 401 5210
(My IP) - - [10/May/2024:13:47:12 +0100] "GET /unauthenticated/css/bundle.min.css?2110001019999999999 HTTP/1.1" 200 186958
(My IP) - - [10/May/2024:13:47:13 +0100] "GET /images/favicons/webmin/android-chrome-192x192.png HTTP/1.1" 200 12818
(My IP) - - [10/May/2024:13:47:13 +0100] "GET /images/favicons/webmin/favicon-32x32.png HTTP/1.1" 200 1787
(My IP) - - [10/May/2024:13:47:14 +0100] "GET /service-worker.js HTTP/1.1" 401 5210
(My IP) - (me) [10/May/2024:13:47:17 +0100] "POST /session_login.cgi HTTP/1.1" 302 0
(My IP) - (me) [10/May/2024:13:47:17 +0100] "GET / HTTP/1.1" 200 89677
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /service-worker.js HTTP/1.1" 200 141
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /unauthenticated/css/fonts-roboto.min.css?2110001019999999999 HTTP/1.1" 200 971
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /unauthenticated/js/defaults.js?2110001019999999999 HTTP/1.1" 200 12463
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /unauthenticated/css/palettes/nightrider.min.css?2110001019999999999 HTTP/1.1" 200 25577
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /service-worker.js HTTP/1.1" 200 141
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /unauthenticated/css/palettes/gunmetal.min.css?2110001019999999999 HTTP/1.1" 200 12338
(My IP) - (me) [10/May/2024:13:47:18 +0100] "GET /unauthenticated/css/bundle.min.css?2110001019999999999 HTTP/1.1" 200 186958
(My IP) - (me) [10/May/2024:13:47:19 +0100] "GET /unauthenticated/js/bundle.min.js?2110001019999999999 HTTP/1.1" 200 506849
(My IP) - (me) [10/May/2024:13:47:20 +0100] "GET /extensions/stats/stats.min.js?2110001019999999999 HTTP/1.1" 200 2546
(My IP) - (me) [10/May/2024:13:47:20 +0100] "POST /index.cgi HTTP/1.1" 200 1
(My IP) - (me) [10/May/2024:13:47:20 +0100] "POST /index.cgi HTTP/1.1" 200 1135
(My IP) - (me) [10/May/2024:13:47:20 +0100] "GET /sysinfo.cgi HTTP/1.1" 200 19684
(My IP) - (me) [10/May/2024:13:47:20 +0100] "GET /unauthenticated/fonts/KFOlCnqEu92Fr1MmWUlfBBc4.woff2 HTTP/1.1" 200 15828
(My IP) - (me) [10/May/2024:13:47:20 +0100] "GET /images/favicons/webmin/favicon-32x32.png HTTP/1.1" 200 1787
(My IP) - (me) [10/May/2024:13:47:24 +0100] "GET /stats.cgi?xhr-stats=general&sdata=1 HTTP/1.1" 200 676
(My IP) - (me) [10/May/2024:13:47:29 +0100] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 13735


** miniserv.error messages

(May 09 is the last time I ran restart-by-force-kill)

[09/May/2024:14:23:05 +0100] miniserv.pl started
[09/May/2024:14:23:05 +0100] Using MD5 module Digest::MD5
[09/May/2024:14:23:05 +0100] Using SHA512 module Crypt::SHA
[09/May/2024:14:23:05 +0100] PAM authentication enabled
[09/May/2024:14:30:58 +0100] Reloading configuration
[09/May/2024:15:35:27 +0100] Reloading configuration
[09/May/2024:23:05:37 +0100] miniserv.pl started
[09/May/2024:23:05:37 +0100] Using MD5 module Digest::MD5
[09/May/2024:23:05:37 +0100] Using SHA512 module Crypt::SHA
[09/May/2024:23:05:37 +0100] PAM authentication enabled
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)
Too many connections (26) from IP (my IP)

**There is no date on the error messages, but my IP address is different today than yesterday, so I know the error messages are from today.

Yesterday after I ran restart-by-force-kill I didn't have anymore issues, as is the pattern.  I receive errors, I run restart-by-force-kill, I can work then, the next morning when I come in I start receiving the errors and can't work.


Let me know what other information I can provide.

-Michele

**Comment by iliajie** [comment]
> Too many connections (26) from IP (my IP)
> Too many connections (26) from IP (my IP)

The only cause I can think of is that you set **Enable real-time monitoring** option to **Yes, forced** in **Theme Configuration: Dashboard and real-time monitoring** page, and then opened multiple Webmin tabs.

**Comment by michele654** [comment]
It is set to Yes.   Not Yes, forced.

And I don't use multiple Webmin tabs.


-Michele

**Comment by iliajie** [comment]
It isn't clear what's wrong. Sorry! You'll need to take a closer look at your setup.

**Comment by michele654** [comment]
My problem is that this setup worked flawlessly since I set up the server in October, and suddenly started failing.  An update to something, webmin, ubuntu, php,... has caused this.  

I don't know what to look at. 

I guess I'll stop using webmin until the next update, and see if that fixes it.  At the moment I have to SSH into the server each time I want to use webmin to run the restart-by-force-kill, so I might as well just work in SSH.

**Comment by kurthuber-dev** [comment]
Unfortunately I also have the same issue, yesterday I made a fresh installation, because I didn't know the tool yet and I get connection lost error messages all the time 
Ubuntu 22.04.4

**Comment by iliajie** [comment]
> Unfortunately I also have the same issue, yesterday I made a fresh installation, because I didn't know the tool yet and I get connection lost error messages all the time Ubuntu 22.04.4

Could you provide a screenshot of the page where you're seeing the issue? Also, could you check what is logged in the Network tab in your browser's console?

**Comment by kurthuber-dev** [comment]
> > Unfortunately I also have the same issue, yesterday I made a fresh installation, because I didn't know the tool yet and I get connection lost error messages all the time Ubuntu 22.04.4
> 
> Could you provide a screenshot of the page where you're seeing the issue? Also, could you check what is logged in the Network tab in your browser's console?

no matter which side
I get the following error messages

![image](https://github.com/webmin/webmin/assets/75269638/981b9616-ebd4-4f9c-a409-92648db41e27)
![image](https://github.com/webmin/webmin/assets/75269638/7f741db1-9d80-44f4-9dfe-c3c96d517a63)

**Comment by iliajie** [comment]
> My problem is that this setup worked flawlessly since I set up the server in October, and suddenly started failing.

Can you try to connect to your Webmin instance using IP address and see if that changes anything?


> I get the following error messages

Interesting! Did you have any IP control configured in **IP Access Control** page?

Can you fully reload the page, does it work for you? If so, try to disable **Real-time monitoring** by going to **Theme Configuration: Dashboard and real-time monitoring** page and see if that changes anything.

**Comment by michele654** [comment]
I found another link that sounded similar, that talked about updating the Theme in Theme Configuration.  

Although the Authentic Theme version did not change, performing the update anyway seems to have made the problem go away. 

Perhaps kurthuber-dev can try that?

As for your questions, Yes, I do IP Control in webmin.  I didn't try it with an IP address before I did the update of the theme, so I can't answer that question.

-Michele

**Comment by kurthuber-dev** [comment]
> > I found another link that sounded similar, that talked about updating the Theme in Theme Configuration.
> > https://forum.virtualmin.com/t/command-shell-no-longer-working-after-lastest-update/126128
> 
> This was fixed, yet should not be related.
> 
> > Although the Authentic Theme version did not change, performing the update anyway seems to have made the problem go away.
> 
> I don't see how that could help!
> 
> Did you try to reload the page in the first pace or tried another browser?

All settings are default so no IP access settings or changes to the real-time monitoring. When I reload the page it has no connection at all, then I have to restart the service so that something is displayed again.
Browser error changes permanently from “Connection has been reset - ERR_CONNECTION_RESET” to “192.168.2.178 has closed the connection unexpectedly - ERR_CONNECTION_CLOSED”.

@michele654 Theme update unfortunately didn't help either, I also switched to the latest development version of Authentic Theme as a test - same problem.

**Comment by iliajie** [comment]
That's still isn't clear what's causing it!

Did you configure any limits in **Webmin ⇾ Webmin Configuration: Ports and Addresses** page?

What is the output of:

```
grep ^max /etc/webmin/miniserv.conf
```

**Comment by chrystophe** [comment]
Hello,

I have several Webmin servers and I have exactly the same problem on some of the servers that I have updated.
I had to update: **Maximum concurrent connections per IP** and **Maximum concurrent connections per network** to **150**.

`#tail -f /var/webmin/miniserv.error is spammed by Too many connections (26) from IP`

**Comment by michele654** [comment]
Previously @iliajie asked if I had tried going in by IP address.

For the last 3 days I first try by domain name and receive the error, then I go in by IP address and can work, without forcing the restart.

Hopefully that gets us a step closer to understanding what's happening so it can be fixed!

-Michele

**Comment by iliajie** [comment]
> I first try by domain name and receive the error, then I go in by IP address and can work, without forcing the restart.

That was my obvious first guess. Now, I hope you're not using Cloudflare and forgetting to mention it, right? 🙂

**Comment by michele654** [comment]
> > I first try by domain name and receive the error, then I go in by IP address and can work, without forcing the restart.
> 
> That was my obvious first guess. Now, I hope you're not using Cloudflare and forgetting to mention it, right? 🙂

Not using Cloudflare...  

This is a server hosted at THG in London.

**Comment by kurthuber-dev** [comment]
i only use ip address no domain

**Comment by iliajie** [comment]
> I had to update: **Maximum concurrent connections per IP** and **Maximum concurrent connections per network** to **150**.
> 
> `#tail -f /var/webmin/miniserv.error is spammed by Too many connections (26) from IP`

What is this IP address? Is it some random IP address, or is it the IP of your client machine or some other _familiar_ to you IP address? What does this network address look like anyway? I mean, the first two parts of the IPv4 address?

Also, what's the output of this command `ss -tnlp | grep 10000` on the system where Webmin runs.

For testing purposes, if you edit the `/etc/webmin/miniserv.conf` file and add `allow=1.2.3.4`, where `1.2.3.4` is the IP address of your client machine, restart Webmin &mdash; do you still have this issue happening?

We need to narrow down the problem. I suspect that something or someone is making too many connections to your Webmin instance, causing _miniserv_ to reject that connection. If it rejects all connections, then it might be a bug in Webmin.

**Comment by graceless70** [comment]
Hi, I too am experiencing this issue. 
(Rocky 9.3 Webmin 2.111-1)
I added 'maxconns=' in miniserv.conf. 

Started at 200.. worked for a bit (after service restart)
then to 400, ... worked for a bit more (after service restart)
then got to 8000 worked for a bit. (after service restart)
then started getting issue again, so set to 80000, restarted service and still having issue.

Too many connections (26) from IP.

***** Where is the connection count cached?  *****

Added allow=x.x.x.x (client IP) seemed to allow me back in for a short while. (ironically, I was on may way to limit to client IP's of admins when I got locked out)

This is the service status a couple of minutes after the last restart of the service:

# systemctl status webmin
● webmin.service - Webmin server daemon
     Loaded: loaded (/usr/lib/systemd/system/webmin.service; enabled; preset: disabled)
     Active: active (running) since Mon 2024-05-20 12:47:03 NZST; 4min 2s ago
    Process: 16405 ExecStart=/usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
   Main PID: 16406 (perl)
      Tasks: 33 (limit: 11109)
     Memory: 361.3M
        CPU: 12.543s
     CGroup: /system.slice/webmin.service
             ├─16406 /usr/bin/perl /usr/libexec/webmin/miniserv.pl --nofork /etc/webmin/miniserv.conf
             ├─16470 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16471 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16479 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16501 /usr/libexec/webmin/authentic-theme/index.cgi
             ├─16609 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16610 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16611 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16612 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16613 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16614 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16615 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16616 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16617 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16618 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16619 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16620 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16621 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16622 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16623 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16624 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16625 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16626 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─16628 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─17407 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17429 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17443 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17454 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17465 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17488 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17513 /usr/libexec/webmin/authentic-theme/403.cgi
             ├─17515 /usr/libexec/webmin/authentic-theme/403.cgi
             └─17533 /usr/libexec/webmin/authentic-theme/403.cgi

Something is buggy . . .

**Comment by graceless70** [comment]
Looking at miniserv.pl @ line 822 it looks like it has reference to 'maxconns_per_ip'

			# Check the number of connections from this IP
			$ipconnmap{$peera} ||= [ ];
			$ipconns = $ipconnmap{$peera};
			if ($config{'maxconns_per_ip'} >= 0 &&
			    @$ipconns > $config{'maxconns_per_ip'}) {
				print STDERR "Too many connections (",scalar(@$ipconns),") from IP $peera\n";
				close(SOCK);
				next;
				}

Try setting in miniserv.conf:

'maxconns_per_ip=xxxx'

NOTE: I had mine at 400. Went from Too many connections (26) to Too many connections (36)
I've gone for 4000 and will see how I go

**Comment by iliajie** [comment]
If you have too many connections, you should investigate them to determine where they are coming from &mdash; 200 connections are already way too many!

**Comment by graceless70** [comment]
Looking at the blame in the .py in github this code was created 4 years ago so strange how it started happening with this version. My old centos machines that I was replacing with an older version of webmin did not have this issue.

I did have 3 session running in different browsers. However I do believe there is an underlying issue you may want to investigate.  
       
       The connection number in the .error did not seem to correlate with the limits set in the .conf. 

Anyway. Thanks... I'm working now.

**Comment by gotanynudesx** [comment]
Same here, same error, random times, I have to I have to stop and start the service to get back on.

**Comment by Satnet** [comment]
Same here, been having it for months. Loses connection, even the CSS styling goes away and it just looks bad.
I've reinstalled my entire server and I still have the same issue.

**Comment by iliajie** [comment]
> Same here, been having it for months. Loses connection, even the CSS styling goes away and it just looks bad.

Do you access Webmin directly or via a proxy?

**Comment by iliajie** [comment]
> > > Same here, been having it for months. Loses connection, even the CSS styling goes away and it just looks bad.
> > 
> > 
> > Do you access Webmin directly or via a proxy?
> 
> Directly

Does Webmin really receive all those connections? Where are they coming from?

**Comment by jcameron** [comment]
@iliaross could the issue be that the theme is now sending more background requests?

**Comment by iliajie** [comment]
Theme, to collect stats, doesn't send more than one request at a time, and only after 1 second delay.

But I should switch theme stats to use sockets, maybe.

**Comment by iliajie** [comment]
Jamie, could you also log what page is getting accessed when connection is getting blocked and logged to _miniserv.log_ file? It would be easier to understand what's going on.

**Comment by jcameron** [comment]
Can't we see this from the users' browser debug logs above though?

**Comment by iliajie** [comment]
> Can't we see this from the users' browser debug logs above though?

No, I mean like:

```
[29/May/2024:17:02:22 +0300] Too many connections (25) from IP 10.211.55.2 : /stats.cgi
```

**Comment by jcameron** [comment]
We can't log the request in that case, because the connection is closed before even reading the HTTP request to limit the impact from DOS attacks.

**Comment by iliajie** [comment]
> We can't log the request in that case, because the connection is closed before even reading the HTTP request to limit the impact from DOS attacks.

It should be possible to do this at least in debugging mode; otherwise, there is no way to know which request it was.

**Comment by jcameron** [comment]
Since we allow 25 connections per IP, it should be possible to see all the previous successfully requests in miniserv.log before the one that went over this limit..

**Comment by iliajie** [comment]
> Since we allow 25 connections per IP, it should be possible to see all the previous successfully requests in miniserv.log before the one that went over this limit..

This operation requires thoughtful efforts.

**Comment by jcameron** [comment]
Do we have a system I can login to that's seeing this issue? That would be useful to debug it ... I suspect it's some unusual browser-server interaction that's leaving a lot of connections hanging.

**Comment by chrystophe** [comment]
> > I had to update: **Maximum concurrent connections per IP** and **Maximum concurrent connections per network** to **150**.
> > `#tail -f /var/webmin/miniserv.error is spammed by Too many connections (26) from IP`
> 
> What is this IP address? Is it some random IP address, or is it the IP of your client machine or some other _familiar_ to you IP address? What does this network address look like anyway? I mean, the first two parts of the IPv4 address?

**IPV4 no random !**

> We need to narrow down the problem. I suspect that something or someone is making too many connections to your Webmin instance, causing _miniserv_ to reject that connection. If it rejects all connections, then it might be a bug in Webmin.

**This surprises me because I filter with firewallD or iptables the IPV4 that can connect to webmin**

To answer in summary:
All addresses authorized to connect to webmin are IPV4 and have been the same for several years.
I noticed something else: My old servers which have not been updated, for dev reasons. have the same problem, so it can only come from the browser/server discussion??
--> I use Google Chrome. I will test with another browser.

**Comment by jcameron** [comment]
Note that the connection limits are per-IP, so even if some attacker is spamming connections to your system it shouldn't effect legitimate users. Unless they are all coming in via some proxy, in which case the IPs will all look the same to Webmin.

**Comment by iliajie** [comment]
> Unless they are all coming in via some proxy, in which case the IPs will all look the same to Webmin.

Yeah, I've asked this question already and the user said no.

Despite that, I can see how a legitimate connection can be reaching limits. If an admin ignores the warning and sets **Enable real-time monitoring** to **Yes, forced** in **Theme Configuration: Dashboard and real-time monitoring** page, and the server is performant enough to handle all those connections at the same rate (~1 second per query), then opening multiple tabs where each tab is making a call could actually lead to it. Even though I couldn't reproduce it on my old and laggy MacBook, I'm pretty sure it's theoretically possible. So the test would be to completely disable real-time monitoring and see how it goes then.

Other than that or being behind a proxy, I don't see how this could be a wrongdoing on Webmin's side.

**Comment by michele654** [comment]
Here's what I know or have learned about this issue since I first opened it.

I am not behind a proxy, I see my IP address in the logs when it rejects the additional connections.
I am the only person that uses Webmin on the server.
I do not open multiple tabs to Webmin,
I have Webmin limited by IP address on who can connect to it.
I have Realtime Monitoring on in Theme Configuration, but not Forced.
My process that I have performed for many years did not change, only Webmin's response changed.
Others have seen this changed behavior as well, confirming it is not something specific to me.
If I log in using the IP address of my server rather than a domain name, I don't get the errors.

Hope this helps point to something that might resolve the issue.

-Michele

**Comment by iliajie** [comment]
> If I log in using the IP address of my server rather than a domain name, I don't get the errors.
> I have Realtime Monitoring on in Theme Configuration, but not Forced.

 1. If you open Network tab in browser's console, how often `stats.cgi` file is getting called, e.g.:
 
 
    <img width="1433" alt="image" src="https://github.com/webmin/webmin/assets/4426533/11a5a8ef-d43c-407a-8e6f-a03e1a98e4da">

  2. If you disable realtime monitoring and still use the domain name to log in, do you continue to get the original issue?

**Comment by michele654** [comment]
> > If I log in using the IP address of my server rather than a domain name, I don't get the errors.
> > I have Realtime Monitoring on in Theme Configuration, but not Forced.
> 
>     1. If you open Network tab in browser's console, how often `stats.cgi` file is getting called, e.g.:
> 

When I go in by IP address, I see this.

![image](https://github.com/webmin/webmin/assets/11981087/1c75f3ca-34b7-4d29-9096-ba70458b3b39)

Note there is only one call to stats, and I tried very hard not to mark out the fact that it does not have the lock icon, as if it was called using http, not https.


When I go in by domain name, I get this (going to the File Manager triggers it..)

![image](https://github.com/webmin/webmin/assets/11981087/7218a1e5-9ba3-4f62-be3b-5254569f961f)


One other note, going in by domain caused my IP address session to fail.  This was a situation where I had 2 tabs open for Webmin.  I had to run restart-by-force-kill to get back in.



>     2. If you disable realtime monitoring and still use the domain name to log in, do you continue to get the original issue?

It appears that disabling realtime monitoring allows me to function using the domain name.  I can say better on Monday, but I've done more in Webmin by domain name in the last few minutes than I've been able to for weeks.

-Michele

**Comment by jcameron** [comment]
Does the domain name resolve to the same IP address that you're testing with?

**Comment by michele654** [comment]
> Does the domain name resolve to the same IP address that you're testing with?

Yes.

**Comment by jcameron** [comment]
Wow, this is a mystery! It's very hard to debug unless I can reproduce it myself unfortunately..

Do you have any chrome extensions installed?

**Comment by iliajie** [comment]
> Restarted the webmin service, quickly disabled the real-time monitoring... and that seems to stabilize things.

The upcoming Webmin with the new Authentic theme will address that issue by using WebSockets to collect stats.

**Comment by michele654** [comment]
> Wow, this is a mystery! It's very hard to debug unless I can reproduce it myself unfortunately..
> 
> Do you have any chrome extensions installed?

I run Firefox...

I've encountered my problem going in by domain name with Realtime monitoring turned off.  Still no problems when I access by IP address.

-Michele

**Comment by jcameron** [comment]
Do you have a valid SSL certificate for the domain name?

**Comment by michele654** [comment]
> Do you have a valid SSL certificate for the domain name?

Yes.

**Comment by markslatter** [comment]
I've run Webmin religiously for many years and have it running on about 15 servers, VM's and LXC containers.  I don't do any fancy setup, normally roll with the default settings other than maybe putting an IP restriction in.  Like everyone else here, I too am experiencing the same problems across multiple Ubuntu servers.  Even fresh installs.  I've tried re-installing Webmin with no luck.  I setup a new server last week on Contabo (great prices) and have the exact same problem - in the middle of using it,  I get "Can't establish a connection to the server".

After reading through this thread, it's definitely an overloaded connection issue - but no idea what is causing them.  Switching to Framed Theme still creates too many connections, but at least it's not losing the connection.  It's not pretty, and some functionality is lost (like the File Manager) but I can use most of the Menu options that I need.

I'm an avid fan of Webmin, even with all the naysayers back in the day, so would love to have the reliable functionality back.  I get that some people want to tinker with its appearance and that's fine, but for me the reliability of the interface is more important.  Here's to hoping the next upgrade somehow corrects the problem.

**Comment by iliajie** [comment]
Thanks for your feedback!

> I've run Webmin religiously for many years and have it running on about 15 servers

Do you use FastRPC in any way?

**Comment by markslatter** [comment]
Hi iliaross,

I am not running anything extra on the servers other than a LAMP stack or Docker.  All headless.  I'm not sure what I'd use FastRPC for so I'm going to go with No, I don't use it =)  Sorry for my ignorance on that front.

After reading through the thread yesterday, I went and looked at the webmin error log and it's loaded with too many connection errors.  I don't fiddle with changing the default port, or tweaking anything other than only allowing from a specific IP address on some of the servers (ones outside of my networks).  Typically I just point to the IP Address:10000  On my local dev station, my PC is plugged into the same unmanaged switch as the VM, so no firewall in between and I don't have any firewall running on the VM....all very odd and I wish I could put my finger on the issue for you.

Thanks very much.

**Comment by iliajie** [comment]
> On my local dev station, my PC is plugged into the same unmanaged switch as the VM, so no firewall in between and I don't have any firewall running on the VM....all very odd and I wish I could put my finger on the issue for you.

What if you limited access to your Webmin instance by configuring the **IP Access Control** page in **Webmin ⇾ Webmin Configuration** to allow only your IP?

**Comment by markslatter** [comment]
That is a good idea iliaross, 

I will give that a try and let you know.  However the error logs only show it's my IP address connecting.  Sometimes I can restart webmin via SSH and it runs fine for a while....sometimes it's as soon as I connect.  I will continue to keep an eye out for some sort of pattern and report here!   Thanks for the idea!

**Comment by iliaross** [comment]
> That is a good idea iliaross,
> 
> I will give that a try and let you know. However the error logs only show it's my IP address connecting. Sometimes I can restart webmin via SSH and it runs fine for a while....sometimes it's as soon as I connect. I will continue to keep an eye out for some sort of pattern and report here! Thanks for the idea!

The only thing I can think of is that the collection of real-time stats is going rogue. However, in the new Webmin release, this won't be a problem anymore since we will use WebSockets for this purpose.

**Comment by markslatter** [comment]
Thanks Iliajie,

I have yet to find any rhyme or reason so look forward to the next version!

Thanks so much.

**Comment by iliajie** [comment]
> I am also experiencing this issue across 5 different installs of Ubuntu.
> 
> 2x Ubuntu 16.04 1x Ubuntu 18.04 and 2x Ubuntu 24.04 (one in docker, one a fresh install)
> 
> I've disabled the real-time monitoring and charts but still happening and making the Webmin interface unusable for me.

Can you monitor network traffic to understand where those requests are coming from and where they are destined exactly? It would be really helpful.

**Comment by DRGluke** [comment]
[https://pastebin.com/08ZtGmzu](url)

I've used Wireguard to capture everything from the point of attempting to load Webmin to the point of fail, which was before it finished loading the first page.

10.10.7.98 is my local computer and 192.168.36.6 is the VM with Webmin.

Here's the network info from Edge.

![failed](https://github.com/webmin/webmin/assets/57141982/142dc25e-30c8-4028-8664-b25e10bb3c69)

Anything else I can provide?

**Comment by iliajie** [comment]
Thanks for providing a dump!

It seems that the client cannot establish a TLS connection with the server. The connection is getting reset, and the client keeps trying until it hits the rate limit on the Webmin side. Have you tried a different browser with all extensions disabled? Does it make a difference?

If not, then I suggest visiting **Webmin ⇾ Webmin Configuration: SSL Encryption** page and checking the SSL-related options, particularly the allowed SSL ciphers. Alternatively, for debugging purposes, try disabling SSL entirely and see if the issue persists from there.

Also, see if raising the limits in **Webmin ⇾ Webmin Configuration: Ports and Addresses** page makes any difference and observe how it affects the issue.

Furthermore, are you connecting directly to Webmin, or are you using a proxy?

**Comment by DRGluke** [comment]
> It seems that the client cannot establish a TLS connection with the server. The connection is getting reset, and the client keeps trying until it hits the rate limit on the Webmin side. Have you tried a different browser with all extensions disabled? Does it make a difference?

I've tried using Firefox, things seemed to work a little longer, but still the same issue.  Incognito so that no extensions are active.

> If not, then I suggest visiting **Webmin ⇾ Webmin Configuration: SSL Encryption** page and checking the SSL-related options, particularly the allowed SSL ciphers. Alternatively, for debugging purposes, try disabling SSL entirely and see if the issue persists from there.

I went with the big gun first and disabled SSL entirely (this system isn't public).  The issue seemed to still persist at the same rate.

> Also, see if raising the limits in **Webmin ⇾ Webmin Configuration: Ports and Addresses** page makes any difference and observe how it affects the issue.

I doubled the Max total concurrent and the Max per ip to 100 and 50 respectively.  This seems to have stabilized things a bit at least for now.  I have had it go on me a couple of times still but its a lot less.  I expect I could raise these values further to workaround the issue for now.

> Furthermore, are you connecting directly to Webmin, or are you using a proxy?

Direct connection, there will be some translation between networks via the firewall.  I can run a test connecting to webmin from the same network/subnet to confirm that's not causing any issues.

**Comment by phrenesis82** [comment]
I had the same issue.

systemctl status webmin showed:
pam_unix(webmin:auth): authentication failure; logname= ui=0 euid=0 tty= ruser= rhost= user=root

I did this:
Goto Webmin >> Webmin Configuration >> Authentication >> Use "Never use PAM for Unix authentication " 

Now everything is fixed.

**Comment by iliajie** [comment]
> pam_unix(webmin:auth): authentication failure; logname= ui=0 euid=0 tty= ruser= rhost= user=root
> I did this:
> Goto Webmin >> Webmin Configuration >> Authentication >> Use "Never use PAM for Unix authentication "
> Restart Webmin

Interesting! Thanks! Does it mean that all who's been having this issue had logged in `miniserv.error`:

```
[04/Jul/2024:19:15:34 +0300] PAM test failed - maybe /etc/pam.d/webmin does not exist
```

Also what is the output of the following command on your system where you seeing this issue:

```
grep -Rsi pam /etc/webmin/miniserv.conf
```

**Comment by phrenesis82** [comment]
> > pam_unix(webmin:auth): authentication failure; logname= ui=0 euid=0 tty= ruser= rhost= user=root
> > I did this:
> > Goto Webmin >> Webmin Configuration >> Authentication >> Use "Never use PAM for Unix authentication "
> > Restart Webmin
> 
> Interesting! Thanks! Does it mean that all who's been having this issue had logged in `miniserv.error`:
> 
> ```
> [04/Jul/2024:19:15:34 +0300] PAM test failed - maybe /etc/pam.d/webmin does not exist
> ```
> 
> Also what is the output of the following command on your system where you seeing this issue:
> 
> ```
> grep -Rsi pam /etc/webmin/miniserv.conf
> ```

Hello Iliajie

I deleted my comment because it turned out I was wrong.

For some reason, after changing the PAM Auth and restarting Webmin, it worked for 15 minutes and then broke again. Then it broke nearly immediately after every restart.

What worked for me was increasing max connections and max connections per IP.

**Comment by iliajie** [comment]
Can anyone provide access to the system that is experiencing this issue? It would be helpful to try and see what's wrong exactly. You can email the system's credentials to jamie at webmin dot com and ilia at webmin dot dev.

**Comment by michele654** [comment]
> Interesting! Thanks! Does it mean that all who's been having this issue had logged in `miniserv.error`:
> 
> ```
> [04/Jul/2024:19:15:34 +0300] PAM test failed - maybe /etc/pam.d/webmin does not exist
> ```
> 
No, I don't...

> Also what is the output of the following command on your system where you seeing this issue:
> 
> ```
> grep -Rsi pam /etc/webmin/miniserv.conf
> ```
There is no output when I run this command.

**Comment by iliajie** [comment]
Could Jamie and/or I have access to your system so we can look deeper into the real cause of the issue?

**Comment by michele654** [comment]
Let me ask, since this is the production web server for the company, with several other webservers providing customer services, I suspect the answer will be no...  I'm on the East Coast, the rest of the company is UK, so I won't have an answer until tomorrow.

**Comment by iliajie** [comment]
Thanks! "No" would be an understandable answer! Though it could help a lot. There's no need to provide access to both of us; having it done for Jamie only would be more than enough.

If it's okay, he will share his public key with you.

**Comment by michele654** [comment]
As suspected, the answer for access to the server was declined.


I had an idea....  I use MFA with Webmin, and I see these error messages in the logs each day:

1720443412.188642.0 [08/Jul/2024 13:56:52] (username) - (my ip) global miniserv.pl "failed" "-" "twofactor"
1720443412.188644.0 [08/Jul/2024 13:56:52] (username)- (my ip)  global miniserv.pl "failed" "-" "wrongpass"
1720459960.207048.0 [08/Jul/2024 18:32:40] (username)- (my ip)  global miniserv.pl "failed" "-" "twofactor"
1720459960.207050.0 [08/Jul/2024 18:32:40] (username)- (my ip)  global miniserv.pl "failed" "-" "wrongpass"

I just assumed they were some artifact from the login process, it's always my username, my IP address, and I believe I've been seeing them since before the failures, which is why I never brought it up. Also, because they always coincide with my login, and are not at the quantity of the "max connections from the IP" error that exists in the log.

Is there a chance the background connections are failing because they can't pass the MFA?  I realize this is a long shot, but I started thinking about background connections while reviewing the daily log reports, which include these errors if I logged in or tried to log in.

-Michele

**Comment by iliajie** [comment]
> I started thinking about background connections while reviewing the daily log reports, which include these errors if I logged in that day.

Which are those background connections?

**Comment by michele654** [comment]
> > I started thinking about background connections while reviewing the daily log reports, which include these errors if I logged in that day.
> 
> Which are those background connections?

The discussion above about the multiple requests that are causing the maxconn to be hit from the IP and causing the connection lost.  perhaps my phrase "background connections" was inappropriate, but something from my active session is hitting Webmin and breaking it.


I have additional information for you after discussing this issue with a colleague.

1)  I was (essentially) root when I installed, I sudo -s and then work.  He pointed out that current recommendation is to install as a regular user with sudo (which is what I was, but apparently not how it was meant).  ps does show that webmin is running as root.

2) Although I don't see the PAM errors in the miniserv.log file, I do see them when I run journalctl
Jul 06 18:32:12 (server).com perl[1312]: pam_unix(webmin:auth): authentication failure; logname
= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 06 18:32:13 (server).com webmin[1312]: Webmin starting
Jul 06 18:32:13 (server).com systemd[1]: Started Webmin server daemon.

-Michele

**Comment by michele654** [comment]
Installed, 2.111. at first I received "Connection Lost" immediately. 

I went in and did /etc/webmin/restart-by-force-kill, and then was able to get in, move around, installed updates, could see the file manager (which was usually instant fail).  I could disconnect all the sessions I was never able to log out of due to the failures.

When I went to the command prompt, it was me, as in my user, when the command prompt had root privileges in the past.  So my attempt to run aide-update failed with permission denied.

I thought about it, and realized it was me instead of root based on the command prompt, and thought that I should go back in and sudo and then see if I can run my aide-update.

I clicked on the command line button, and it just stuck at connecting.  I went out, logged out, and tried to log in again.  That's when it seemed to go sideways.

I logged in, gave it my MFA token, it went into Webmin and I saw a new popup, Session expired, asking for my password and token.  It wouldn't take, it kept telling me the OTP was wrong.  Then I saw a message that my IP address was blocked for too many failed authentication attempts.  

**!!WORSE, my user ID and Password was in plaintext in that message!!!**

I did restart-by-force-kill again.  I looked for the block list, found a page from 2009 saying it was /var/webmin/blocked, but that file was empty.  I went in by IP address, got in.  Logged out, logged in with the domain name, got in.  Went to terminal, sudo'd and ran my aide update, and that worked.

It's not perfect, but it's better.  All but that plaintext password...

-Michele

**Comment by michele654** [comment]
Installed, 2.111. at first I received "Connection Lost" immediately. 

I went in and did /etc/webmin/restart-by-force-kill, and then was able to get in, move around, installed updates, could see the file manager (which was usually instant fail).  I could disconnect all the sessions I was never able to log out of due to the failures.

When I went to the command prompt, it was me, as in my user, when the command prompt had root privileges in the past.  So my attempt to run aide-update failed with permission denied.

I thought about it, and realized it was me instead of root based on the command prompt, and thought that I should go back in and sudo and then see if I can run my aide-update.

I clicked on the command line button, and it just stuck at connecting.  I went out, logged out, and tried to log in again.  That's when it seemed to go sideways.

I logged in, gave it my MFA token, it went into Webmin and I saw a new popup, Session expired, asking for my password and token.  It wouldn't take, it kept telling me the OTP was wrong.  Then I saw a message that my IP address was blocked for too many failed authentication attempts.  

**!!WORSE, my user ID and Password was in plaintext in that message!!!**

I did restart-by-force-kill again.  I looked for the block list, found a page from 2009 saying it was /var/webmin/blocked, but that file was empty.  I went in by IP address, got in.  Logged out, logged in with the domain name, got in.  Went to terminal, sudo'd and ran my aide update, and that worked.

It's not perfect, but it's better.  All but that plaintext password...


-Michele

**Comment by surfer92** [comment]
We have the same problem... I try to reinstall, downgrade, and change themes...Noting these helps us.
![image](https://github.com/webmin/webmin/assets/10532609/19b8b120-e6d1-4e34-875f-7b14f22f0c7a)

**Comment by michele654** [comment]
More info, these were in my miniserv.error log from today's work activity.

[10/Jul/2024:13:29:17 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:17 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:17 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:17 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:17 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:18 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:22 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:28 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:29 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:47 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:47 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:47 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:48 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:48 +0100] Too many connections (26) from IP (my IP)
[10/Jul/2024:13:29:49 +0100] Too many connections (26) from IP (my IP)

-Michele

**Comment by michele654** [comment]
> I'm sorry, but this isn't helpful in any way.

Well how about all the details I provided from testing with the nightly build?  Was any of that helpful?

-Michele

**Comment by michele654** [comment]
> Installed, 2.111.202407091553, went in by domain name and at first I received "Connection Lost" immediately.
> 
> I went in and did /etc/webmin/restart-by-force-kill, and then was able to get in by domain name, move around, installed updates, could see the file manager (which was usually instant fail). I could disconnect all the sessions I was never able to log out of due to the failures.
> 
> When I went to the command prompt, it was me, as in my user, when the command prompt had root privileges in the past. So my attempt to run aide-update failed with permission denied.
> 
> I thought about it, and realized it was me instead of root based on the look of the command prompt, and thought that I should go back in and sudo and then see if I can run my aide-update.
> 
> I clicked on the command line button, and it just stuck at connecting. I went out, logged out, (_maybe I just closed the window, in thinking about this that was probably the beginning of this failure: I didn't log out, but just closed the window_) and tried to log in again. That's when it seemed to go sideways.
> 
> I logged in by domain name, gave it my MFA token, it went into Webmin and I saw a new popup, Session expired, asking for my password and token. It wouldn't take, it kept telling me the OTP was wrong. Then I saw a message that my IP address was blocked for too many failed authentication attempts.
> 
> **!!WORSE, my user ID and Password was in plaintext in that message!!!**
> 
> I did restart-by-force-kill again. Tried to go in by domain name, same result: Session Expired, nope, you're not getting back in.
> 
> I looked for the block list, found a page from 2009 saying it was /var/webmin/blocked, but that file was empty. I went in by IP address, got in. Logged out, logged in with the domain name, got in. Went to terminal, sudo'd and ran my aide update, and that worked.
> 
> It's not perfect, but it's better. All but that plaintext password...
> 
> Is that message logged someplace? I tried in the webmin.log, miniserv.log, and miniserv.error and couldn't see it. I would really like to remove that message before it gets into my backups...
> 
> -Michele

In case you missed my feedback from running with the nightly build.

**Comment by jcameron** [comment]
> !!WORSE, my user ID and Password was in plaintext in that message!!!

This is concerning! Can you post a redacted screenshot of the error message?

**Comment by michele654** [comment]
> > !!WORSE, my user ID and Password was in plaintext in that message!!!
> 
> This is concerning! Can you post a redacted screenshot of the error message?

The popup on the screen goes away after a few seconds, but here it is from my logs...

(my IP) - - [09/Jul/2024:19:23:25 +0100] "GET /session_login.cgi?user=(my Username)&pass=(My plaintext password)&twofactor=710840&ajax=1&save=1&failed_twofactor_attempt=4 HTTP/1.1" 403 1020602

-Michele

**Comment by iliajie** [comment]
> (my IP) - - [09/Jul/2024:19:23:25 +0100] "GET /session_login.cgi?user=(my Username)&pass=(My plaintext password)&twofactor=710840&ajax=1&save=1&failed_twofactor_attempt=4 HTTP/1.1" 403 1020602

Duh, I see now which code on the theme side is causing the root password to be logged! It's the session logout screen that helps re-authenticate the session without reloading the page and possibly losing data, e.g.:

<img width="932" alt="image" src="https://github.com/webmin/webmin/assets/4426533/7d132305-ccdb-43b1-8722-e7a92fe54387">

I will fix that to use POST request, as it is risky to use GET for these types of data submits!

---

Nonetheless, I don't see how it's related to the original issue with too many connections!

**Comment by michele654** [comment]
That is the new authentication box I had never seen before.  

1)  It wasn't the root password that was logged, it was my regular username password in the message
2)  My point in the second comment was even though I received those "too many connections" messages, I didn't have any issues with working while using the nightly build from July 9, which was why I was surprised to see the error messages in my log report.

You may want to do more testing on the Session Expired box, I never got it to work for me. 

-Michele

**Comment by thiagobrazil** [comment]
I was having the same issues here. I believe the problem might be a blockage from the internet provider or router on port 10000. Try changing the port to 8484 and increasing the simultaneous connections. It's been two days since I made the change, and it's working. Test it yourselves as well. If the problem returns, I will update you.

Webmin -> Webmin Configuration -> Ports and Addresses
Add Port e.g., 8484, Max Connections 1000

Access by domain IPv4 e.g., https://site.com:8484

![image](https://github.com/webmin/webmin/assets/44044072/94537a83-2c74-4113-a9ff-814d57905fa0)

**Comment by michele654** [comment]
Just FYI, this morning I received the Connection Lost message on the July 09 nightly build when going to the terminal.  I believe this is the first time I've seen it using this build.

responding to above, I always run a non-standard port for webmin.

**Comment by iliajie** [comment]
> You may want to do more testing on the Session Expired box, I never got it to work for me.

Alright, this issue was addressed in the latest nightly build!

I would greatly appreciate it if everyone experiencing this issue could try again with latest nightly build and let us know how it goes for you.

> responding to above, I always run a non-standard port for webmin.

I will need to run more tests with this!

**Comment by michele654** [comment]
I never got around to installing the nightly build, and then I got the 2.200 update and thought it might be in that.

Still failing.  This morning I updated to 2.201, and it fails pretty quickly too.

Does the nightly build have something different than 2.201 that I should be testing?

-Michele

**Comment by iliajie** [comment]
> Does the nightly build have something different than 2.201 that I should be testing?

No, no difference in this regard at all.

**Comment by iliajie** [comment]
> Webmin version	2.111

Webmin 2.201 is already out, and it should solve this problem.

**Comment by adambog** [comment]
> > Webmin version	2.111
> 
> Webmin 2.201 is already out, and it should solve this problem.

sorry, that didn't work for default values:

`maxconns_per_ip=25`
`maxconns_per_net=35`

had to manualy bump them to high values (1500 in my case) in miniserv.conf to be able to use it

webmin version:
`user@host:[~]$ sudo apt-cache show webmin
Package: webmin
Version: 2.201
Architecture: all
Depends: perl, libnet-ssleay-perl, openssl, libauthen-pam-perl, libpam-runtime, libio-pty-perl, unzip, shared-mime-info, tar, libdigest-sha-perl, libdigest-md5-perl, gzip
Recommends: libdatetime-perl, libdatetime-timezone-perl, libdatetime-locale-perl, libtime-piece-perl, libencode-detect-perl, libtime-hires-perl, libsocket6-perl, lynx, qrencode
Pre-Depends: perl
Installed-Size: 185024
Maintainer: Jamie Cameron <jcameron@webmin.com>
Provides: webmin
Replaces: webmin-adsl, webmin-apache, webmin-bandwidth, webmin-bind, webmin-burner, webmin-cfengine, webmin-cluster, webmin-core, webmin-cpan, webmin-dhcpd, webmin-exim, webmin-exports, webmin-fetchmail, webmin-firewall, webmin-freeswan, webmin-frox, webmin-fsdump, webmin-grub, webmin-heartbeat, webmin-htaccess, webmin-inetd, webmin-jabber, webmin-ldap-netgroups, webmin-ldap-user-simple, webmin-ldap-useradmin, webmin-lilo, webmin-logrotate, webmin-lpadmin, webmin-lvm, webmin-mailboxes, webmin-mon, webmin-mysql, webmin-nis, webmin-openslp, webmin-postfix, webmin-postgresql, webmin-ppp, webmin-pptp-client, webmin-pptp-server, webmin-procmail, webmin-proftpd, webmin-pserver, webmin-quota, webmin-samba, webmin-sarg, webmin-sendmail, webmin-shorewall, webmin-slbackup, webmin-smart-status, webmin-snort, webmin-software, webmin-spamassassin, webmin-squid, webmin-sshd, webmin-status, webmin-stunnel, webmin-updown, webmin-usermin, webmin-vgetty, webmin-webalizer, webmin-wuftpd, webmin-wvdial, webmin-xinetd, webmin-filemin, webmin-authentic-theme
Priority: optional
Section: admin
Filename: pool/contrib/w/webmin/webmin_2.201_all.deb
Size: 33720350
SHA256: 60068092a218743f6af8abe44afdf0f671b1cf06bb421a4de06b7a5615f11031
SHA1: 61ab4ca189bb4b3f28816243c084ac2bf3c0f85e
MD5sum: 20a249e5c9bbde4764dcdbab65445eaa
Description: web-based administration interface for Unix systems
  Using Webmin you can configure DNS, Samba, NFS, local/remote filesystems
  and more using your web browser.  After installation, enter the URL
  https://localhost:10000/ into your browser and login as root with your root
  password.
Description-md5: e199469c3ff44f561cbe06e80a4e265f`

**Comment by michele654** [comment]
I previously reported this:

> I never got around to installing the nightly build, and then I got the 2.200 update and thought it might be in that.
> 
> Still failing. This morning I updated to 2.201, and it fails pretty quickly too.
> 
> Does the nightly build have something different than 2.201 that I should be testing?
> 
> -Michele


Before your reply of:

> > Webmin version	2.111
> 
> Webmin 2.201 is already out, and it should solve this problem.

-Michele

**Comment by iliajie** [comment]
> had to manualy bump them to high values (1500 in my case) in `miniserv.conf` to be able to use it

Alright! Thanks for the feedback! I hope it helps someone.

> Does the nightly build have something different than 2.201 that I should be testing?

Neither Jamie nor I can reproduce this problem, so it's very hard to fix something we don't understand. Sorry!

**Comment by TimDressel** [comment]
@iliaross I have a fresh Ubuntu server 24.04 running webmin 2.202 having the same issues. 

I don't github normally, but if there is a way to PM me, please do and I'll see if there is a way I can give you access to this server - I can't expose it directly to the internet.

Cheers,

Tim

**Comment by markslatter** [comment]
I just wanted to add that I'm on the latest version of Webmin and honestly haven't seen the issue across multiple servers in some time.... maybe it was another package that was causing the issue and upgrades since then along with updates in Webmin have fixed it?  Maybe some of us were using pieces that others weren't and that's the hit/miss results where others were having no problem (or still are having problems)?  But I'm not experiencing it recently which is awesome (for me).

Thanks so much for your dedication and follow up @iliaross.  I'm sorry I couldn't put my finger on the cause or fix, but really appreciate your efforts to work through it.

**Comment by iliaross** [comment]
> Thanks so much for your dedication and follow up @iliaross. I'm sorry I couldn't put my finger on the cause or fix, but really appreciate your efforts to work through it.

Thank you so much for your kind words! It means a lot!

**Comment by chris001** [comment]
Seems like a firewall issue or SELinux rule restricting network use.
Is this resolved for all now?

**Comment by chris001** [comment]
This might be a long shot, but what if you run webmin in front of an apache web proxy, does it show the same issue?

**Comment by NMCPaul** [comment]
Is there any more movement on this?  Fresh install on AlmaLinux 9.4.  If I restart webmin, `systemctl status webmin` shows the following:

```
systemctl status webmin
● webmin.service - Webmin server daemon
     Loaded: loaded (/usr/lib/systemd/system/webmin.service; enabled; preset: disabled)
     Active: active (running) since Tue 2024-09-03 18:54:13 EDT; 1s ago
    Process: 2556057 ExecStart=/usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
   Main PID: 2556058 (miniserv.pl)
      Tasks: 2 (limit: 23161)
     Memory: 25.8M
        CPU: 462ms
     CGroup: /system.slice/webmin.service
             └─2556058 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf

Sep 03 18:54:12 d2 systemd[1]: Starting Webmin server daemon...
Sep 03 18:54:13 d2 systemd[1]: Started Webmin server daemon.
```

I reload the page three times, and now it looks like this:

```
systemctl status webmin
● webmin.service - Webmin server daemon
     Loaded: loaded (/usr/lib/systemd/system/webmin.service; enabled; preset: disabled)
     Active: active (running) since Tue 2024-09-03 18:54:13 EDT; 1min 33s ago
    Process: 2556057 ExecStart=/usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
   Main PID: 2556058 (miniserv.pl)
      Tasks: 27 (limit: 23161)
     Memory: 63.6M
        CPU: 4.206s
     CGroup: /system.slice/webmin.service
             ├─2556058 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556586 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556598 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556599 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556602 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556603 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556604 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556610 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556615 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556720 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556723 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556724 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556725 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556730 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556731 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556736 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556737 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556738 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556841 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556848 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556849 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556850 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556851 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556852 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556853 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             ├─2556858 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
             └─2556859 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf

Sep 03 18:54:12 d2 systemd[1]: Starting Webmin server daemon...
Sep 03 18:54:13 d2 systemd[1]: Started Webmin server daemon.
```

And I'm locked out.  Every refresh appears to spin up quite a few processes.  My `maxconns` is set to 500, but that's a) not working, and b) not a fix.  Pretty sure it's not supposed to spin up 3-5 processes each time I reload a page.  And real-time monitoring is off.

Does anyone have any suggestions?

**Comment by chris001** [comment]
When it was locking you out, was it using a self-signed cert?

**Comment by michele654** [comment]
> I just wanted to add that I'm on the latest version of Webmin and honestly haven't seen the issue across multiple servers in some time.... maybe it was another package that was causing the issue and upgrades since then along with updates in Webmin have fixed it? Maybe some of us were using pieces that others weren't and that's the hit/miss results where others were having no problem (or still are having problems)? But I'm not experiencing it recently which is awesome (for me).
> 
> Thanks so much for your dedication and follow up @iliaross. I'm sorry I couldn't put my finger on the cause or fix, but really appreciate your efforts to work through it.

I just want to echo this, I haven't experienced the issue in some time, and I really appreciate your continued work on this even though you couldn't recreate it.  And fixing the logging in plaintext issue!  I would not have been able to continue using Webmin if that issue continued...

**Comment by NMCPaul** [comment]
> When it was locking you out, was it using a self-signed cert?

Yes, the one that comes with Webmin.

**Comment by iliajie** [comment]
> > When it was locking you out, was it using a self-signed cert?
> 
> Yes, the one that comes with Webmin.

Which browser are you using? Are you the only one using this system?

**Comment by iliajie** [comment]
But did the issue stop as soon as you got a legitimate (not self-signed) SSL certificate?

Also, when the issue happened, were all the mentioned browsers open at the same time, or not? if they were,  were they trying to access Webmin with the SSL security screen showing, or did you bypass it and had an active login session?

Furthermore, did the browser even give you an option to bypass the SSL security warning at all (using a button), or was there no option at all and you had to type _`thisisunsafe`_ to bypass it?

Finally, what is your domain's TLD, and did the issue occur when accessing Webmin using the IP address?

**Comment by NMCPaul** [comment]
As soon as I put in a proper, minted cert the issue stopped.  Webmin ceased locking me out and ceased spawning 3-4 processes per refresh.

No, the browsers mentioned were tried one after another as a troubleshooting step.  At no time were there multiple instances of Webmin open.

The browser DID give me the option to bypass and accept the self-signed cert.

My domain was [servername].nmc.edu, and the issue did occur with the same frequency/regularity when using the IP instead of the domain name.

**Comment by iliajie** [comment]
This is useful! Thanks! I'll take a closer look in a few days, once I finish working on something else.

By the way, since `.edu` TLDs are not on the HSTS preload list by default, did you happen by any change to enforce it using the `ssl_hsts` option in the `miniserv.conf` file?

**Comment by NMCPaul** [comment]
Negative.  `ssl_hsts` was and is still set to `0`.

Incidentally, I did block SSLv2, SSLv3, TLSv1.0, and TLSv1.1 in case those matter.

**Comment by iliaross** [comment]
Reopened, as this was closed by an automated cleanup run.

⚠️ If the issue is resolved, please take a moment to close it to help keep the project organized.
