### ISSUE TITLE
Problem with redirection in RHEL

### ISSUE THREAD

**Issue by Cheroman-PCs** [webmin/webmin#2513]
For testing purposes, I installed Webmin on two Debian-based distros (Mint 21.3 and Ubuntu Server 24.04.2 LTS) and two RHEL-based distros (AlmaLinux 10.0 Server with GNOME GUI and Rocky Linux Cinnamon 9.5).
I found that if I connect to the Debian-based distros, using my example as a web browser from Windows, http://server06.local:10000 is automatically redirected to https://server06.local:10000. However, on the RHEL-based distros, when I connect from Windows by typing http://server06.local:10000 in any web browser, http://server06.local:10000 is not automatically redirected to https://server06.local:10000. I have tried to check that everything is the same, both in the Debian-based and RHEL-based distros, and it seems that I have come to the conclusion that it may be a bug, so it is reported there.

**Comment by iliaross** [comment]
Hello,

Thanks for the heads up!

The issue you're describing should already be fixed—check this thread https://github.com/webmin/webmin/issues/2504.

**Comment by Cheroman-PCs** [comment]
> Hello,
> 
> Thanks for the heads up!
> 
> The issue you're describing should already be fixed—check this thread [#2504](https://github.com/webmin/webmin/issues/2504).

I already checked this thread, but it doesn't fix the redirection problem, al menos en mi caso.

**Comment by iliaross** [comment]
> I already checked this thread, but it doesn't fix the redirection problem, al menos en mi caso.

Did you try the latest development version of Webmin from https://download.webmin.dev?

**Comment by Cheroman-PCs** [comment]
> Did you try the latest development version of Webmin from https://download.webmin.dev?

I'm not that expert, I don't know how to install it, and which one I should install to test on Rocky Linux 9.5 Cinnamon, could you help me?

**Comment by iliaross** [comment]
> I'm not that expert, I don't know how to install it, and which one I should install to test on Rocky Linux 9.5 Cinnamon, could you help me?

Yeah, you could just do:

```
dnf -y update https://download.webmin.dev/webmin-2.402.202507052035-1.noarch.rpm
```

**Comment by Cheroman-PCs** [comment]
> Sí, podrías simplemente hacer:
> 
> ```
> dnf -y update https://download.webmin.dev/webmin-2.402.202507052035-1.noarch.rpm
> ```

Thanks, it's working now, but I think it's not working as it should, because it's loading in http, without redirecting to https, as it does in Ubuntu Server 24.04.2 LTS and Mint 21.3 Cinnamon, even if you put http it redirects to https

**Comment by iliaross** [comment]
Yeah, and instead we’re showing a label saying that it’s not secure (not HTTPS). It can be clicked to go to secure connection though.

**Comment by Cheroman-PCs** [comment]
> Sí, y en su lugar, mostramos una etiqueta que indica que no es segura (no es HTTPS). Sin embargo, se puede hacer clic para acceder a la conexión segura.

Oh okay, but I'll leave it as a suggestion, it would be good if the operation was the same as in Ubuntu Server 24.04.2 LTS and Mint 21.3 Cinnamon, since I think that would be the right thing to do.

**Comment by iliaross** [comment]
If you have a valid SSL certificate installed, we will send an HSTS header, then after the first secure visit the browser will remember and force HTTPS for that Webmin instance on every future visit. This kind of connection upgrade will look for the user as redirect.

**Comment by Cheroman-PCs** [comment]
> Si tiene instalado un certificado SSL válido, le enviaremos un encabezado HSTS. Tras la primera visita segura, el navegador recordará y forzará el uso de HTTPS para esa instancia de Webmin en cada visita posterior. Esta actualización de conexión buscará al usuario como redirección.

Okay, perfect.

**Comment by Cheroman-PCs** [comment]
Well, thank you very much for your help. Best regards.

**Comment by iliaross** [comment]
You're welcome! I will close this ticket then.
