### ISSUE TITLE
No way to enable disabled systemd unit

### ISSUE THREAD

**Issue by jrmain** [webmin/webmin#430]
Webmin 1.810 on Ubuntu 16.04.1. If I create a new systemd service using Webmin, configuring it to start at boot, after saving the service it appears in the Bootup and Shutdown list. If I then edit the service, disabling 'Start at boot time', the service no longer appears in the list. I can use `systemctl enable` to re-enable the service, but I can't find a way to enable it using Webmin. The Bootup and Shutdown module is configured for systemd.

**Comment by jcameron** [comment]
On your system, if you run `systemctl list-units --full --all` does it show the service that you created?

**Comment by jrmain** [comment]
If the service is enabled, I see it in that list. If it's disabled, I don't see it in that list. I'm enabling it with ```systemctl enable``` and disabling it with ```systemctl disable```. Whether it's enabled or disabled, I can check its status with ```systemctl status```. And whether it's enabled or not, the actual source for the service exists in ```/lib/systemd/system```.

**Comment by jcameron** [comment]
Ok, that explains it. Unless there is some flag to `systemctl list-units` , I don't see how Webmin can know that the service exists.

**Comment by jrmain** [comment]
I thought ```systemctl list-units --all``` might show it, but it doesn't. However, it does appear in the list produced by this command (even when disabled): ```systemctl list-unit-files```.

**Comment by jcameron** [comment]
Thanks - I confirmed this, and will also use list-unit-files to find disabled units in the next release.

**Comment by jrmain** [comment]
I'm not sure if the fix for this made it into version 1.820, but if it did, it doesn't seem to have fixed the problem.

**Comment by jcameron** [comment]
If you apply the patch from https://github.com/webmin/webmin/commit/f30810180505de616dcc4f99ea9137d8ca28cb34 to Webmin on your system, does it fix the problem?

**Comment by jrmain** [comment]
Looked at `/usr/share/webmin/init/init-lib.pl` and found that it already has the changes. The disabled services are still missing from Webmin's Bootup Services page. `systemctl list-unit-files` shows the services as 'disabled'. Note: the missing services work fine; I can control them using systemctl. But I created them, and it's entirely possible that I did something improperly that's contributing to Webmin not seeing them. Let me know if I can provide any more information.

**Comment by jcameron** [comment]
Can you post the output from `systemctl list-unit-files` on your system (or at least the line for the problem action) ?

**Comment by jrmain** [comment]
`bf1942-server.service                      disabled
bf2-server.service                         disabled`
and
`mcserverstatus.service                     disabled
minecraft-server.service                   disabled`

Four services in total that are missing from the Webmin Bootup list. Weirdly, when I first updated to Webmin 1.820, I tested this, and the services appeared even when disabled. Now they don't. Cached data?

**Comment by jcameron** [comment]
Ok, I think I see the issue. Try out the commit I just added to this ticket..

**Comment by jrmain** [comment]
Made the change indicated to /usr/share/webmin/init/init-lib.pl. Restarted Webmin (not sure if that's necessary). Unfortunately the oddball services still don't appear in Webmin's Bootup list.

**Comment by jcameron** [comment]
What output do you get if you run `systemctl show -- minecraft`

**Comment by jrmain** [comment]
```Restart=no
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
FailureAction=none
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=0
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
ExecMainStartTimestampMonotonic=0
ExecMainExitTimestampMonotonic=0
ExecMainPID=0
ExecMainCode=0
ExecMainStatus=0
MemoryCurrent=18446744073709551615
CPUUsageNSec=18446744073709551615
TasksCurrent=18446744073709551615
Delegate=no
CPUAccounting=no
CPUShares=18446744073709551615
StartupCPUShares=18446744073709551615
CPUQuotaPerSecUSec=infinity
BlockIOAccounting=no
BlockIOWeight=18446744073709551615
StartupBlockIOWeight=18446744073709551615
```

**Comment by jcameron** [comment]
Odd that there is no `UnitFileState` line, which systemd units normally have.

How was this `minecraft` startup action created?

**Comment by jrmain** [comment]
I used the Webmin Bootup and Shutdown module, configured for systemd. For example, my first test was to create fnord.service using Webmin:
```
Service name: fnord(.service)
Service description: A service to test systemd
Commands to run on startup: /bin/bash /home/jrivett/fnord.sh
Start at boot time? Yes
```

After creating the service, I confirmed that it was showing up in the list of services on the Bootup and Shutdown page and checked its configuration:
```
[Unit]
Description=A service to test systemd
[Service]
ExecStart=/bin/bash /home/jrivett/fnord.sh
[Install]
WantedBy=multi-user.target
```

When I changed `Start at boot time` to `No`, the service stopped appearing in the Bootup and Shutdown list. I wasn't able to figure out what was going on, so I started using systemctl instead, which worked fine. I went ahead and created several more services, including the minecraft server one I posted about earlier. They all work fine, and I use systemctl to enable/disable/stop/start them. Then I submitted this issue report, you made some changes to Webmin, and that brings us up to date.

Interestingly, if I now create a new service using Webmin, the same way I did with my first test, it all seems to work perfectly. Presumably the changes you've made account for this. I tried refreshing Webmin modules, restarting Webin, and restarting the server, and the service is still listed. My original test service (above) still exists, but is not listed in Webmin. When I compare the output of `systemctl show` for the two test services, the only differences are the ID, name, description and path. Which is just weird.

I'll try recreating the minecraft service to see if that works, and I'll let you know what happens.

**Comment by jrmain** [comment]
Created a new minecraft server service using Webmin. It showed up in the bootup list. Configured the service to NOT start at boot, and it disappeared from the bootup list. Used `systemctl enable` to re-enable it, and it again appears in the bootup list. Why is this service acting differently from the test service I just created? I'm perfectly willing to believe that I'm just doing something stupid, but have no idea what that might be.

**Comment by jcameron** [comment]
How did the creation or config of your `test` service differ from your `minecraft` service?

**Comment by jrmain** [comment]
It didn't, which is just bizarre. Shall I repeat the experiment?

**Comment by jcameron** [comment]
Yes, please do - I'd be interested to know what triggers to creation of the non-working service.

**Comment by jrmain** [comment]
This just keeps getting weirder. Keep in mind that I'm able to use `systemctl` to manage these services without any problems. I created a pair of test services using the Webmin Bootup and Shutdown (B&S) page. The only difference between them is in `Commands to run on startup`: one just runs a bash script, while the other runs a bash script via `su` and `screen`. Based on my previous testing, I expected the simpler service to appear in the Webmin B&S list regardless of status, and the more complicated one to disappear from the list when disabled. Imagine my surprise when the **exact opposite** happened. At this point I'm officially out of testing ideas. Something very weird is going on, and I don't know if it's in systemd (which certainly has its share of issues) or Webmin. Let me know if you'd like me to try anything else.

**Comment by jrmain** [comment]
Sorry to pester you, but I was wondering if you've had any more ideas about this. I'm currently leaning towards getting rid of systemd altogether. The systemd debate has valid arguments on both sides, but in practical terms, this issue with Webmin (regardless of where the problem actually exists) is tipping the scales firmly back to upstart.

**Comment by jcameron** [comment]
Could it be that the one which is working is a script in `/etc/init.d` rather than a systemd unit?

**Comment by jrmain** [comment]
I checked /etc/init.d and found nothing related to any of my test services. Note that I'm using Webmin's Bootup and Shutdown page ('create a new systemd service') to create these test services. And doing that *does* create what appears to be the appropriate files in /lib/systemd/system. It should be possible to reproduce this behaviour using current Webmin on a vanilla Ubuntu 16 server.

**Comment by jcameron** [comment]
Just to check, which Webmin version are you running there? Because we are up to 1.830 now.

**Comment by jrmain** [comment]
I'm running 1.831, which is actually a commit you added here on October 14 (above). Should I revert to the current release version?

**Comment by jcameron** [comment]
No, that version should work. What's odd is that I just test with the latest released Webmin on a fully updated Ubuntu 16.04 system, creating an action with the same command as in your example above, and I was able to enable and disable it just fine.

**Comment by jrmain** [comment]
I now have three test services that are all identical except for service name (Description). The commands to run (ExecStart) are identical. One works as expected, and the other two do not: they disappear from Webmin's Bootup & Shutdown list when they are disabled (via Webmin or systemctl). The third one (not working properly) I created this morning with Webmin.

Obviously this is very weird. I wish I could see what was happening behind the scenes with Webmin. Is there a chunk of code I could run to emulate what Webmin is doing when it builds the B&S list?

**Comment by jrmain** [comment]
I suppose we should also compare the 'Configurable options for Bootup and Shutdown', on the off chance that I've got something set improperly. But that wouldn't explain why one of the test services works fine.

**Comment by jcameron** [comment]
Did you perhaps change anything on the "Configurable options" page?

If you post your `/etc/webmin/init/config` file here, I can compare the settings.

**Comment by jrmain** [comment]
Initially I was using the defaults, but then changed a few things when I started running out of ideas. Anyway, here's the current contents of the config file:

```no_chkconfig=1
init_base=/etc/
init_mode=systemd
soft_links=1
local_down=
rc_dir=
show_opts=0
status_check=2
desc=2
rc_conf=
daemons_dir=
order=1
sort_mode=0
shutdown_command=poweroff
darwin_setup=
atboot_product=webmin
start_stop_msg=1
reboot_command=reboot
boot_levels=2 3 5
inittab_id=id
init_dir=/etc/init.d
startup_dirs=
init_info=1
local_script=
order_digits=2
expert=1
hostconfig=
plist=

**Comment by jcameron** [comment]
You may want to try setting it back to the defaults, by copying `/usr/share/webmin/init/config-debian-linux` over that file.

**Comment by jrmain** [comment]
Tried that. No difference.

**Comment by jcameron** [comment]
I am totally mystified then, sorry.

**Comment by jrmain** [comment]
Is there perhaps a line or two of debugging code I could add to /usr/share/webmin/init/init-lib.pl, to see what's happening? I can't help wondering, since running `systemctl list-unit-files` from the command line shows the missing services, whether the code that parses that command's results is the source of the problem (sub list_systemd_services in /usr/share/webmin/init/init-lib.pl).

**Comment by jcameron** [comment]
One thing you could try is installing the very latest 1.832 version of Webmin from http://www.webmin.com/devel.html . It may be that whatever issue you're seeing has been fixed on my dev systems already.

**Comment by jrmain** [comment]
I installed the development version and confirmed I'm now running 1.832. Unfortunately, it didn't help with the problem. `systemctl list-unit-files` still shows all the services created using Webmin, but Webmin itself shows some services only if they are enabled.

I decided to poke around with the code in `sub list_systemd_services` in `/usr/share/webmin/init/init-lib.pl`. I commented out the three lines that use `opendir`, and now all the services appear. Yay! Is it possible that the `opendir` code is broken, and causing the following `systemctl list-unit-files` code to fail?

**Comment by jcameron** [comment]
Where these the three lines you removed :

```
opendir(UNITS, &get_systemd_root());
push(@units, grep { !/\.wants$/ && !/^\./ } readdir(UNITS));
closedir(UNITS);
```

**Comment by jrmain** [comment]
Yes, those were the three lines I commented out.

**Comment by jcameron** [comment]
That is very surprising, as removing those lines should *reduce* the number of systemd units that are scanned by webmin.

**Comment by jrmain** [comment]
Unless the code is crapping out and preventing the following code from running properly.

**Comment by jcameron** [comment]
No, in that case you'd see an error message.

Other than the action you created, do any others have this same problem where they disappear if disabled?

**Comment by jrmain** [comment]
Yes, most of the services I created with Webmin do that: all but one of ten. The test services, as well as several for game servers like the Minecraft one I mentioned earlier.

I'm not a Perl expert, but is there really no way for the code in question to fail silently and cause the following code to be skipped?

I moved the `systemctl list-unit-files` code above the `opendir` code and uncommented the `opendir` code, and that also works fine. It seems clear to me that with the `opendir` code first, the other code is never being run. But like I said, I don't really know Perl.

It would be helpful if there was some way to add debug messages to show what's happening. But in the meantime, I'm just going to leave the `opendir` code commented out. It's obviously not necessary, it's not adding anything useful, and it's causing problems.

**Comment by jcameron** [comment]
The only possible cause I can think of is if some systemd unit is causing the later call to `systemctl show` to fail. The code for that is here : https://github.com/webmin/webmin/blob/master/init/init-lib.pl#L2051

It might be useful to print the STDERR from that call.

**Comment by jrmain** [comment]
Okay, a couple of things. First, you're going to have to be a little more specific about adding the STDERR print in init-lib.pl. I'm sure I could figure it out eventually, but... Secondly, it looks like the `opendir` code is just one of several different methods used to build a list of services, and there's apparently a lot of overlap. From my perspective, if the list I'm seeing is complete (and it seems to be), the `opendir` code doesn't seem necessary, and if it's actually causing problems, why not get rid of it? But I guess what works for me may not work for everyone.

**Comment by jcameron** [comment]
What I was thinking of was changing the code :

```
        $out = &backquote_command("systemctl show -- ".join(" ", @args).
                                  " 2>/dev/null");
```

to :

```
        $out = &backquote_command("systemctl show -- ".join(" ", @args));
```

**Comment by jrmain** [comment]
I re-enabled the `opendir` code in its original location and made the change you suggested in your last comment. Navigated to the Webmin B&S list, which again is missing several services. But I don't see anything interesting in the Apache error log or `/var/webmin/miniserv.error`, or anywhere else. Should I be looking somewhere in particular for STDERR messages in the context of Webmin running on its own Apache instance?

**Comment by jblipphaus** [comment]
I think I found the problem at line https://github.com/webmin/webmin/blob/master/init/init-lib.pl#L2051. `@units` contains names like `ssh@.service`, and `systemctl show -- ssh@.service` results in `Failed to get properties: Unit name ssh@.service is not valid.`. This also messes up other units in the batch of 100 units processed.
As a workaround I set the batch size from 100 to 1 and that fixed the problem for me (there were quite a few services missing, the list went from ~100 to ~180).
It would be probably better to filter those units with `xxx@` or` xxx@.service` (`xx@x` or `xx@x.service` are valid, though, it's only invalid when the `@` is at the end or directly before the `.service`.

**Comment by jrmain** [comment]
That would certainly explain what I'm seeing. I look forward to an official fix. Meanwhile I've just commented out the offending code to fix the problem.

**Comment by jblipphaus** [comment]
I made a nicer fix and after
`@units = &unique(@units);`
I inserted
`@templates = grep { /\@$/ || /\@\.service$/ } @units;
@units = grep { !/\@$/ && !/\@\.service$/ } @units;`.
It would be nice if the templates could be represented in Webmin somehow, so you can spawn services from the templates. I also noticed with a test service that was started from a template that it was shown in the list while running, but shown as "not running" and "start at boot" was true, but it was running and NOT enabled.
Also I changed the `()` in https://github.com/webmin/webmin/blob/master/init/init-lib.pl#L2029 to include the `.service` to prevent duplicates in the `@units` list.

**Comment by jcameron** [comment]
Thanks for the suggestion! I guessed it was something like this, but could never re-produce it.

A fix for this will be included in the next Virtualmin release.

**Comment by maehschaf** [comment]
Hello,

Is it allowed to reopen this case or post comments on closed issues? If not, please excuse!

I have Webmin 1.881 on an OpenSUSE Leap 15 fresh install. Startup behaviour "Systemd" or "Detect Automatic" does not make any difference.

Unfortunately I do not see several disabled services in bootup menu, i.E. smb.service
As soon as I enable smb.service, it appears in the list.

By the way: nmbd is always in the list, no difference whether enabled or not.

I found out that this corresponds to the behaviour of the command `systemctl list-units --all`

As soon as I comment out the three lines I found in the message above, I see all services in all states, including smb.

Hope this helps to improve webmin...

Regards,
Martin
