### ISSUE TITLE
Serious showstopper bind9 malfunction (solved) (needs code to detect and heal system).

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#870]
* `bind9` running as authoritative master name server, on debian jessie 8, was causing a severe web service outage by failing to serve **ANY** DNS records from **multiple** top level server domains hosted by and managed by virtualmin / webmin (latest versions), running on a fully updated operating system.
* **ALSO, and even more critically, ZONE TRANSFER TO SLAVES (_AXFR_) WAS FAILING SILENTLY!!!**
```
root@server1:~# dig @localhost example.com SOA

; <<>> DiG 9.11.0-P3 <<>> @localhost example.com SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 37456
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.com.            IN      SOA

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Mar 16 12:17:28 EDT 2018
;; MSG SIZE  rcvd: 47
```
* Error message returned by legitimate DNS lookup requests on the domain, was `SERVFAIL`. ?!?!
* `bind9` version specs:
```
$ named -V
BIND 9.11.0-P3 <id:4801fbc>
running on Linux x86_64 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018
built by make with defaults
compiled by GCC 4.9.2
compiled with OpenSSL version: OpenSSL 1.0.1t  3 May 2016
linked to OpenSSL version: OpenSSL 1.0.2l  25 May 2017
compiled with libxml2 version: 2.9.1
linked to libxml2 version: 20901
compiled with zlib version: 1.2.8
linked to zlib version: 1.2.8
threads support is enabled
```
* Errors in `/var/log/syslog`:
```
$ tail -20000 /var/log/syslog | grep named | grep "example.com" | grep "journal rollforward failed"
Mar 16 11:48:50 server1 named[6065]: zone server1.example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
Mar 16 11:48:50 server1 named[6065]: zone example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
Mar 16 11:50:01 server1 named[27941]: zone example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
Mar 16 11:50:01 server1 named[27941]: zone server1.example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
Mar 16 12:02:53 server1 named[28603]: zone example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
Mar 16 12:02:53 server1 named[28603]: zone server1.example.com/IN (unsigned): journal rollforward failed: journal out of sync with zone
```
* Webmin/Virtualmin **probably** _changed the zonefile while bind was running without freezing it_.
* To fix this, first stop `bind9`: `service bind9 stop`
* Then remove the journal file for the zone. On Debian, the journal file is located (astonishingly) in `/var/lib/bind/`, in the same directory as the zone (why are these zone files in `/var/lib/bind/` when they should probably be in a more suitable place such as `/etc/bind/zones/` ?!):	
`rm /var/lib/bind/*.jnl`
* Then start `bind9` again: `service bind9 start`
* To avoid the problem next time, before changing a zonefile, `webmin/virtualmin` should **freeze the zone**:
`rndc freeze example.com`
* Then edit your zonefile and finally thaw it: `rndc thaw example.com`
* **This `bind9` `SERVFAIL` runtime complete system failure bug probably occurred because `rndc` was silently failing due to failure to connect issue regarding `rndc.key` and/or `localhost` issue (possibly due to fact that the `rndc.key` was not defined before it was used in the `named.conf` !!), and virtualmin/webmin was not reporting the failure of `rndc` as a notification to the web admin console!**

**Comment by gnadelwartz** [comment]
so the fix should be not to change zone file if `rndc freeze` fails and report failure?

**Comment by chris001** [comment]
Yes, reporting failure of `rndc` would, at the very least, bring attention to the fact that there's something seriously wrong with `rndc` runtime config, which **must be fixed first**, before webmin can be permitted to modify any zone file. Modifying a zone file which has not been successfully frozen, will definitely lead to runtime `SERVFAIL` on crucial DNS `bind9` domain infrastructure.

**Comment by chris001** [comment]
Better fix is to intelligently heal `rndc` at runtime (detect error and fix its cause), and retry the `rndc freeze` command.

**Comment by chris001** [comment]
Notes on `rndc` updates, from `/usr/share/doc/bind9/README.Debian`:
```
Upgrading from earlier bind9 packages:
-------------------------------------

If you installed an early version of the Debian bind9 packages, prior to
version 1:9.2.0-2 to be more precise, you may have an /etc/bind/rndc.conf
configuration file still on your system.  There's nothing wrong with that,
and if you've explicitly configured keys for using rndc you may well want to
leave things exactly as they are!

However, since 9.2.0 BIND 9.X has supported an rndc.key file that both named
and rndc will read to obtain a shared key for rndc use against a daemon on
the same host.  The rndc-confgen program will easily create a suitable key
file.  To take advantage of this mechanism, you may want to:

        remove the /etc/bind/rndc.conf file
        remove the rndc key specification in the /etc/bind/named.conf file

        rndc-confgen -r /dev/urandom -a

Alternatively, you can 'purge' the bind9 packages and reinstall them and you
will end up with the new behavior since it is now the default.

This is more secure than using a static key that isn't generated on a per-host
basis, and is an easy alternative to more complex key schemes if you only need
to use rndc to talk to named on the same host.
```

**Comment by chris001** [comment]
An extra button to clear journal might seem nice to have, but it'd put an added burden on the sys admin to go to that screen and hit that button, when webmin can easily detect the error by itself.  
Best is, webmin automatically detects the `rndc` fail error, and webmin runs that button code (`stop`, `rm *.jnl`, `start`).

**Comment by jcameron** [comment]
Webmin will always freeze and unfreeze a zone before updating it with rndc .. but it doesn't freeze before editing. In what cases is this necessary?

**Comment by gnadelwartz** [comment]
it's needed when dynamic updates are done. freeze force the updates from journal written to zone file
https://ftp.isc.org/isc/bind9/cur/9.11/doc/arm/Bv9ARM.ch04.html#dynamic_update

**Comment by chris001** [comment]
@jcameron @gnadelwarty Yes, dynamic updates are enabled (with `allow-update`) for some zones on this virtualmin server, because of developing the requested feature "dynamic dyn DNS" #456 
Probably safest to always `freeze`, then edit, then `thaw`, the zone, to prevent this type of catastrophic silent failure of a master authoritative DNS server.  BIND is a database server in this respect and needs to protect the "transaction".

**Comment by jcameron** [comment]
OK, so you have some other tool editing the DNS records outside of Virtualmin via direct calls to BIND?

Freezing and thawing before and after editing would fix this, but would take some work to implement.

**Comment by imcdona** [comment]
This is related to https://www.virtualmin.com/node/56380 In short, the BIND module will RESTART bind after making changes to a zone when it doesn't think rndc is setup properly.

**Comment by imcdona** [comment]
And since the zone wasn't frozen before the changes were made to the zone, that zone is now corrupt on bind restarting.

**Comment by jcameron** [comment]
I'll add this to my TODO list for future support, but it's complex as there are many places in Webmin that update DNS zones.

**Comment by chris001** [comment]
@jcameron Zone data was only every edited, and then webmin's "Save and verify" button hit, from **inside webmin/virtualmin in the DNS records pages**.  Work had begun on trying to get dynamic updates working on webmin.  However, that work had halted.  Enabling the `allow-updates` setting in the zone, was as far as it had gotten, in practice, because `rndc` was malfunctioning, because, as I discovered here, `webmin` has been, apparently, without knowing any better, updating zones in ways that inadvertently corrupt the journal files, which consequently causes `rndc` to inexplicably and silently fail, and the zone itself to silently and permanently fail with `SERVFAIL` it's pretty much the most serious type of malfunction of BIND9 DNS that you can possibly have.

**Comment by jcameron** [comment]
So really what webmin should do when editing a zone file is freeze first (which dumps out any dynamic changes), edit it, and then thaw the zone, and finally reload with rndc?

**Comment by imcdona** [comment]
@jcameron Yes, freeze, make changes, thaw, reload the zone.

**Comment by imcdona** [comment]
If you try to freeze a non dynamic zone rndc complains. It may be easier to attempt to freeze all zones prior to updating. If it succeeds, then thaw and reload afterwards. Otherwise continue as usual.

**Comment by chris001** [comment]
Also important to report to the sys admin unexpected failures of `nslookup` and `rndc`, and if possible, auto fix the cause.  There might be unknown edge cases where `freeze` and `thaw`, and deleting the journal files, doesn't repair the zone and it continues to return `SERVFAIL`.

**Comment by jcameron** [comment]
Ok, I just checked in a patch that will freeze zones before editing and thaw them afterwards - but only when editing via the BIND module. Please take a look ..

**Comment by chris001** [comment]
Off topic: some time ago there was a comment from @swelljoe about @jcameron unit tests and functional black box tests running on local machines in a variety of operating system distros, is there thought given on when to upload those tests to a `tests` folder here on github so that they be called easily by Travis, every time a community contributor does a pull request for example @gnadelwartz , and every time you add new code by pushing a commit? Isn't it best to have Travis do the hard work of auto running the tests here on github, on the entire code base, every time new code is added, and proposed to be added?

**Comment by gnadelwartz** [comment]
the simplest check would be to let perl execute every *.cgi and *.pl.
typical output should be:

- empty response and return code 0 for *.pl
- `WEBMIN_CONFIG not set at web-lib-funcs.pl line 4355.` and returncode !0 for *.cgi

**Comment by gnadelwartz** [comment]
looks good. should fix the problem.

**Comment by imcdona** [comment]
There is still an issue that needs to be addressed. Records added to a dynamic zone via nsupdate don't appear in Webmin unless you freeze the zone first.

**Steps to reproduce:**

**1.** Add a record to dynamic DNS zone via RFC 2136 (eg nsupdate)
**2.** Open the zone in question in Webmin
**3.** Note how the records added to the zone in question don't appear in Webmin
**4.** Click the "Freeze Zone" button in Webmin for the zone in question
**5.** Note how the records you added in step 1 are now visible in Webmin

**Comment by jcameron** [comment]
Webmin only ever reads the zone files - it won't see dynamically added records.

**Comment by imcdona** [comment]
@jcameron It will if you freeze/unfreeze the zone prior to displaying the records.

**Comment by chris001** [comment]
@imcdona  @jcameron 
To make BIND9 commit the journals, which contain updates to all dynamic zones, to the zone files on disk, webmin could just do `rndc sync -clean`:
```
sync [-clean]    Dump changes to all dynamic zones to disk, 
                and optionally remove their journal files.
```
This change would probably fix #928 (DNS zone displayed by webmin is totally missing all dynamically updated DNS records).

**Comment by imcdona** [comment]
@jcameron @chris001 Updated a zone via RFC 2136 and ran `rndc sync -clean` and Webmin picked up the changes as expected. :)

**Comment by chris001** [comment]
@imcdona That's awsome!
@jcameron It'd be great for the webmin BIND module to do the same `rndc sync -clean`, prior to performing a _CRUD operation_ on a zone (especially **Read** and **Update**), so that it'll process and display all BIND DNS zone record data accurately, without omissions or errors.

**Comment by jcameron** [comment]
Sure, I could do that. How does running `rndc sync -clean` differ from freezing and thawing though?

**Comment by imcdona** [comment]
@jcameron The end result of running `rndc sync` vs `rndc freeze` and `rndc thaw` is the same. The zone files are synced with the journal files. Since we're not making changes to the zone, we merely need the master zone to reflect what's been written to the journal since the zone was last synced, `rndc sync` is the correct way to go about it.

The `-clean` option not only syncs the journal file with the mast zone, it also deletes the journal file. I'm unclear as to the use case for the -clean option so I just assume leave it off. Although specifying it doesn't break anything aside from deleting the journal files which get re-written anyway.

**Freeze** - suspends updates to a dynamic zone. It also causes changes in the journal file to be synced into the master file. **You freeze before you make changes to the master zone file.**

**Thaw** -This causes the server to reload the zone from disk, and re-enables dynamic updates after the load has completed. **You thaw after you're done making your changes to frozen zone file.**

**sync [-clean]**  - Sync changes in the journal file for a dynamic zone to the master file. If the "-clean" option is specified, the journal file is also removed. If no zone is specified, then all zones are synced. **If you simply want the journal file to be synced with the master zone file on disk you sync it.**

**Comment by jcameron** [comment]
Sounds like I should make Webmin just run `rndc sync` every time before reading the zone file?

**Comment by imcdona** [comment]
@jcameron Yes. That would fix the issue. 👍

**Comment by jcameron** [comment]
Ok, I'll have webmin do that in the next release.
