### ISSUE TITLE
Package dependency issues 

### ISSUE THREAD

**Issue by Yarli** [webmin/webmin#955]
Trying to install the latest dev version (1.891) onto a fresh Ubuntu Server:
```
  Operating System: Ubuntu 18.04.1 LTS
            Kernel: Linux 4.15.0-32-generic
      Architecture: x86-64
```
and getting the following errors:
```
Selecting previously unselected package webmin.
(Reading database ... 103158 files and directories currently installed.)
Preparing to unpack webmin_current.deb ...
Unpacking webmin (1.891) ...
dpkg: dependency problems prevent configuration of webmin:
 webmin depends on libauthen-pam-perl; however:
  Package libauthen-pam-perl is not installed.
 webmin depends on apt-show-versions; however:
  Package apt-show-versions is not installed.

dpkg: error processing package webmin (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...
Errors were encountered while processing:
 webmin
```

Tried installing via the debian package using dpkg -i as well as via the repository method too, and both come up with the same errors.
Seems both libauthen-pam-perl and apt-show-versions dependencies are required by webmin but when trying to install these manually I get this:
```
apt install libauthen-pam-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libauthen-pam-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libauthen-pam-perl' has no installation candidate
```

I've also tried using apt --fix-broken install to resolve this but that just uninstalls the half installed webmin and then trying to install the missing dependencies again after running that just gives me the same error about the package being missing, obsoleted etc.

**Comment by jcameron** [comment]
Can you install it with `apt-get install libauthen-pam-perl` ?

**Comment by Yarli** [comment]
I tried that too and sadly I get the same error:
```
root@test_build01:~# apt-get install libauthen-pam-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libauthen-pam-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libauthen-pam-perl' has no installation candidate
```

**Comment by jcameron** [comment]
@Yarli  - are you also on Ubuntu 18 ?

**Comment by simplecloudcontrol** [comment]
Same problem on a new server , downloaded iso from Ubuntu today.

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by Yarli** [comment]
Yes thats correct. Im on 18.04.1 LTS
In my original post i put the version number and platform info :)

Adam French
Systems, Web & Software Development

QueByte Networks

**Comment by simplecloudcontrol** [comment]
Added this repo https://packages.ubuntu.com/bionic/amd64/libauthen-pam-perl/download and it then installed. Then got this issue https://github.com/webmin/webmin/issues/941 but dropped down to 1.880 to correct it.

**Comment by jcameron** [comment]
Can you post your /etc/apt/sources.list file? Because on my test Ubuntu 18 system (a fresh install), that package is available.

**Comment by simplecloudcontrol** [comment]
This is what it looked like after I added the last line. This is for 18.04.1 fresh install

> deb http://archive.ubuntu.com/ubuntu bionic main
deb http://archive.ubuntu.com/ubuntu bionic-security main
deb http://archive.ubuntu.com/ubuntu bionic-updates main
deb http://cz.archive.ubuntu.com/ubuntu bionic main universe

**Comment by jcameron** [comment]
Odd, mine is much longer : 

```
## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.tmpl

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu bionic main restricted
deb-src http://archive.ubuntu.com/ubuntu bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted
deb-src http://archive.ubuntu.com/ubuntu bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu bionic universe
deb-src http://archive.ubuntu.com/ubuntu bionic universe
deb http://archive.ubuntu.com/ubuntu bionic-updates universe
deb-src http://archive.ubuntu.com/ubuntu bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu bionic multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic multiverse
deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner
```

**Comment by simplecloudcontrol** [comment]
That is what i get if I do a 18.04 install and I bet if you do a install of 18.04 and upgrade to 18.04.1 it will match your list of repo's but a fresh install of 18.04.1 I get the short list that I posted. FYI I am using the ubuntu-18.04.1-live-server-amd64.iso downloaded through the cogent communications mirror from yesterday.

**Comment by jcameron** [comment]
Ok, maybe the cause is using a different ISO - I think I did a full server install.

**Comment by Yarli** [comment]
I also used ubuntu-18.04.1-live-server-amd64.iso 

Adam French
Systems, Web & Software Development

QueByte Networks

**Comment by swelljoe** [comment]
In the Virtualmin installer, we enable the universe repository to deal with a lot of missing packages in the base repos. That should resolve the issue, I think.

I think this will do it (we directly add it to the apt.sources list in the installer, but only because add-apt-repository isn't widely available on older distros and Debian yet):

```
$ sudo add-apt-repository universe
```

**Comment by jcameron** [comment]
Agreed, it seems like a possible installer bug that not all required repositories are enabled by default.

@swelljoe do you think this is easily fixable?

**Comment by swelljoe** [comment]
Yeah, it's fixable. Looking at it now, will likely be able to fix it for next version of installer. The way the installer currently enables it, I think, is to just search for the "universe" line and uncomment it. But, obviously, if the sources file doesn't contain a universe line that doesn't happen. I'll just add a step to use `add-apt-repository universe` if that command is available, which should resolve it for modern Ubuntu distros, regardless of what the sources file looks like to start with. (I don't think that command exists on some or all debian versions, but I also don't think they ever ship a stripped down sources file like this.)

**Comment by swelljoe** [comment]
Yeah, it's fixable. Looking at it now, will likely be able to fix it for next version of installer. The way the installer currently enables it, I think, is to just search for the "universe" line and uncomment it. But, obviously, if the sources file doesn't contain a universe line that doesn't happen. I'll just add a step to use `add-apt-repository universe` if that command is available, which should resolve it for modern Ubuntu distros, regardless of what the sources file looks like to start with. (I don't think that command exists on some or all debian versions, but I also don't think they ever ship a stripped down sources file like this.)

**Comment by swelljoe** [comment]
OK, I think it's fixed in git. I'll roll the new version to the repos today. It'll still need testing, but I think it'll work.

**Comment by rostovtsev** [comment]
@swelljoe @jcameron I can confirm that it's fixed on Ubuntu Linux 18.04.1.

**Comment by nicorac** [comment]
Still happens on a freshly installed Ubuntu 20.04 server:
```# apt install webmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 webmin : Depends: libauthen-pam-perl but it is not installable
E: Unable to correct problems, you have held broken packages.
```
To fix it I've executed:
`$ sudo add-apt-repository universe`

**Comment by ThermoMan** [comment]
Still happening on Ubuntu 24.04 Desktop.

I did an `sudo do-release-upgrade` on top of 22.04 Desktop that had Webmin installed. 

I tried `sudo add-apt-repository universe` and it did not help.
I tried (without success)
```
sudo apt-get install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

The command `dpkg --get-selections | grep hold` has no output


```
sudo apt install  webmin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 webmin : Depends: libauthen-pam-perl but it is not installable
          Recommends: libdatetime-perl but it is not installable
          Recommends: libdatetime-timezone-perl but it is not installable
          Recommends: libdatetime-locale-perl but it is not installable
          Recommends: libencode-detect-perl but it is not installable
          Recommends: libsocket6-perl but it is not going to be installed
          Recommends: lynx but it is not installable
          Recommends: qrencode but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I think I am missing some installation source based on 
```
 sudo apt-get install libauthen-pam-perl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libauthen-pam-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libauthen-pam-perl' has no installation candidate
```

```
 cat /etc/apt/sources.list
# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources
```

```
cat /etc/apt/sources.list.d/ubuntu.sources
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu
Suites: noble-security
Components: main restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

What source do I need to add in order to be able to install that perl package (Google has _not_ been my friend in this search)

**Comment by chris001** [comment]
In ububtu, `libauthen-pam-perl` is on the `universe` repo.
https://launchpad.net/ubuntu/+source/libauthen-pam-perl

```
:~ # apt show libauthen-pam-perl
Package: libauthen-pam-perl
Version: 0.16-6build3
Priority: optional
Section: universe/perl
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Perl Group <pkg-perl-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 79.9 kB
Depends: perl (>= 5.38.2-3.2build1), perlapi-5.38.2, libc6 (>= 2.4), libpam0g (>= 0.99.7.1)
Homepage: https://metacpan.org/release/Authen-PAM
Download-Size: 23.0 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu noble/universe amd64 Packages
Description: Perl interface to PAM library
 The Authen::PAM module provides a Perl interface to the PAM library.
 It provides compatibility with both newer and older PAM libraries,
 allowing the use of any of the known names for a give constant.
```

**Comment by chris001** [comment]
From @iliaross comment on:
https://github.com/webmin/webmin/issues/1966#issuecomment-1653934423

Try this:
```
cd /usr/share/webmin/
./setup-repos.sh -f
```

**Comment by ThermoMan** [comment]
apt show gives me a very differnt answer

```
apt show libauthen-pam-perl
Package: libauthen-pam-perl
State: not a real package (virtual)
N: Can't select candidate version from package libauthen-pam-perl as it has no candidate
N: Can't select versions from package 'libauthen-pam-perl' as it is purely virtual
N: No packages found
```

I have no `/usr/share/webmin/` directory - I assume it got deleted in the OS upgrade process?

I did download the script per the install instructions on https://webmin.com/download/

```
 curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5268  100  5268    0     0  32048      0 --:--:-- --:--:-- --:--:-- 32121

$ sudo sh setup-repos.sh
Setup repository? (y/N) y
  Downloading Webmin key ..
  .. done
  Installing Webmin key ..
  .. done
  Setting up Webmin repository ..
  .. done
  Cleaning repository metadata ..
  .. done
  Downloading repository metadata ..
  .. done
Webmin package can now be installed using apt-get install --install-recommends webmin command.
```

but I get the same answer
```
sudo apt-get install --install-recommends webmin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 webmin : Depends: libauthen-pam-perl but it is not installable
          Recommends: libdatetime-perl but it is not installable
          Recommends: libdatetime-timezone-perl but it is not installable
          Recommends: libdatetime-locale-perl but it is not installable
          Recommends: libencode-detect-perl but it is not installable
          Recommends: libsocket6-perl but it is not going to be installed
          Recommends: lynx but it is not installable
          Recommends: qrencode but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by ThermoMan** [comment]
If someone has a working install, please post your `/etc/apt/sources.list.d/ubuntu.sources` file and I'll manually edit mine to match

**Comment by chris001** [comment]
> If someone has a working install, please post your `/etc/apt/sources.list.d/ubuntu.sources` file and I'll manually edit mine to match

I have no `/etc/apt/sources.list.d/ubuntu.sources` on ubuntu 24.04 (dist-upgraded from 18.04 every LTS), only these:
```
azure-cli.list
azure-cli.list.distUpgrade
docker.list
docker.list.distUpgrade
mod-pagespeed.list
mod-pagespeed.list.distUpgrade
ondrej-ubuntu-nginx-mainline-noble.sources
virtualmin.list
virtualmin.list.distUpgrade
webmin.list
webmin.list.distUpgrade
```

Note, virtualmin is also installed.

Here is the `webmin.list`:
```
deb [signed-by=/usr/share/keyrings/ubuntu-webmin-developers.gpg] https://download.webmin.com/download/newkey/repository stable contrib
```

Here is `/etc/apt/sources.list` for noble 24.04 which is the ubuntu sources list:
```
deb http://us.archive.ubuntu.com/ubuntu/ noble main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ noble-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ noble universe
deb http://us.archive.ubuntu.com/ubuntu/ noble-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ noble multiverse
deb http://us.archive.ubuntu.com/ubuntu/ noble-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu noble-security main restricted
deb http://security.ubuntu.com/ubuntu noble-security universe
deb http://security.ubuntu.com/ubuntu noble-security multiverse

```

**Comment by ThermoMan** [comment]
OK, I was able to fix my broken webmin install process by accident.

Because of an update on the VM host machine I was getting Guru Meditation errors and searches suggested the best (only?) fix was to upgrade to VirtualBox 7 directly from Oracle instead of using the Ubuntu managed repo.

I followed the instructions here: https://kifarunix.com/upgrade-virtualbox-6-x-to-virtualbox-7-x-on-ubuntu-debian/?expand_article=1

And after restarting my VMs I added the same repo mentioned to the running VMs as well so that they could get the right extension pack updates.

Then for grins I tried reinstalling webmin.  It just worked.

So either someone at Ubuntu fixed the main repo for all the dependencies or the new repo from Oracle fixed it.
```
echo "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" | \
sudo tee /etc/apt/sources.list.d/virtualbox.list
```

I have no idea what has changed, I'm just glad to be back to being able to remote GUI manage again!

**Comment by chris001** [comment]
Good!  In fact the whole VirtualBox 6.1.xx series is end of life and no longer supported by Oracle, the final 6.1.xx maintenance update 6.1.50 was released in January 2024 for users stuck on older OS, and is known to experience issues on recent Linux kernel  versions - e.g. kernel 6.8 in Ubuntu 24.04.  You do need to run 7.x.
