### ISSUE TITLE
Login redirects to port 10000

### ISSUE THREAD

**Issue by hitmax117** [webmin/webmin#976]
When using Webmin behind a reverse proxy like nginx the login screen redirects to url.com:10000 instead of url.com after a successful login.

**Comment by rostovtsev** [comment]
What is your setup? Do you use SSL?

**Comment by gnadelwartz** [comment]
if you use reverse proxy, you have to tell it webmin also, see: 
http://www.webmin.com/apache.html

Try adding the line "webprefixnoredir=1" to /etc/webmin/config.

**Comment by swelljoe** [comment]
Pretty sure gnadelwartz suggestion is all that's needed here, so closing this ticket.

**Comment by pirate** [comment]
After adding "webprefixnoredir=1" to /etc/webmin/config didn't fix it for me, after restarting and clearing all caches I'm still getting redirects to `:10000`.

**Comment by rostovtsev** [comment]
Is it happening behind Apache?

If you globally set Gray Theme (including login prompt, using Webmin/Webmin Configuration/Themes), will it still do redirect?

**Comment by pirate** [comment]
It's not behind Apache, it's behind a Cloudflare Argo tunnel.  Just confirmed it also still happens with the Gray theme set.

![image](https://user-images.githubusercontent.com/511499/62450200-bda42b00-b720-11e9-86dc-42af123bd476.png)

**Comment by rostovtsev** [comment]
Nick, actually latest Webmin version (1.920+) that ships latest _Authentic Theme_ 19.36+ actually might handle things correctly without being it set `webprefixnoredir` to `1`. 

Can you try to make sure that you're running at least _Authentic Theme_ 19.36, then set it by default (including login screen) and change `webprefixnoredir` option to `0` or drop it completely and restart Webmin service after editing its config file.

Does it help?

**Comment by rostovtsev** [comment]
It's also assumed that `relative_redir` is set to `0` or not present in your config.

**Comment by pirate** [comment]
I tried both 0 and 1, no luck. Haven't tried the new version yet though, thanks for the help so far!

**Comment by rostovtsev** [comment]
What are your Webmin and Authentic Theme versions?

**Comment by Duetro** [comment]
I have the same problem.

Operating system | CentOS Linux 7.6.1810
Webmin version | 1.930 | 
Authentic theme version | 19.39-2

I tried:
relative_redir = unset
webprefixnoredir = unset / 1 / 0

**Comment by rostovtsev** [comment]
Check you Apache proxy and do not set _ProxyPreserveHost On_ directive (other proxies should have familiar option), it will cause redirect after login problem. If you want to log real IP, use `trust_real_ip` option set to `1` in _miniserv.conf_ file, or use UI to change it in _Webmin/Webmin Configuration/IP Access Control/Trust remote IP address provided by proxies_ setting it to _Yes_.

**Comment by groenator** [comment]
I have the same issue using caddy, I tried every configuration possible, nothing helped. When I login it redirects to domain:port_number. 

This is my caddy config. I disable SSL until I fix the issue, otherwise I get banned by let's encrypt. 

```GNU nano 2.7.4                     File: Caddyfile                               
# WebMin
webmin.com:80 {
    tls off
    tls email@gmai.com
    proxy / http://127.0.0.1:10000 {
    transparent
    }
    log stdout
    errors stdout                                                                      header / {
        Strict-Transport-Security "max-age=31536000;"
        X-XSS-Protection "1; mode=block"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
    }
}

**Comment by rostovtsev** [comment]
https://github.com/webmin/webmin/issues/1135

**Comment by user897943** [comment]
So basically the developers don't want to fix this. I'm using traefik and I keep being redirected to 10000, after trying several combinations of the above advice. It really is unacceptable. I get the login page when I go to https://my.server.com, then after submitting my login, it changes to http. I had to turn off SSL in webmin so Traefik would handle the certificate generation via LetsEncrypt, before with SSL on in webmin I could not login at all. I set the redirect_port to 443. WHY IS WEBMIN CHANGING TO HTTP? Is it possible to please include a redirect_to_https option please? So that upon enabling, webmin would redirect to https even if ssl was set to off. That way it would possibly work, because after submitting my login and being redirect to the http://my.server.com, if I manually amend to https://my.server.com then I get the webmin interface as intended. I think in my case this would work.

**Comment by iliarostovtsev** [comment]
> So basically the developers don't want to fix this. I'm using traefik and I keep being redirected to 10000,

It has been fixed a long time ago.  Have you rad this? https://github.com/webmin/webmin/issues/1135#issuecomment-565818024

> which is great BUT.... WHY IS WEBMIN CHANGING TO HTTP? 443 is https

Webmin doesn't automatically change it. Check your proxy config.

**Comment by user897943** [comment]
Yes I have read that entire page. And this one. It is NOT fixed believe me or I would not be writing this.
I have to do the above to gain access.
As I write this I am trying regex rules in traefik, I have a regex redirect to catch the url and convert http to https, but that leads to a 404 error.

**Comment by iliarostovtsev** [comment]
>  after trying several combinations of the above advice.

What have you tried?

What Webmin version are you using?

**Comment by user897943** [comment]
I got it to login without redirecting, but in order to achieve this I had to go to:
Webmin > Webmin configuration > Authentication
on Authentication type I selected Disable session authentication
under Local authentication, I selected Always require username and password
after those, I clicked the green Save button.
Now, rather than getting a web page with the login boxes, I get a standard http auth, and if I enter the incorrect user and pass, I get unauthorised message.
This "hack" is okay except that now I no longer get to use TOTP (2 factor) which is disgraceful
What can you infer from the above?

My miniserv.conf is below:

`
port=10000
root=/usr/share/webmin
mimetypes=/usr/share/webmin/mime.types
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
ssl=0
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
listen=10000
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
ipv6=0
premodules=WebminCore
server=MiniServ/1.953
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=authentic-theme
passdelay=1
failed_script=/etc/webmin/failed.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
login_script=/etc/webmin/login.pl
sudo=1
error_handler_404=404.cgi
error_handler_401=401.cgi
error_handler_403=403.cgi
nolog=\/stats\.cgi\?xhr\-stats\=general
logouttimes=myusername=600
twofactor_provider=totp
sockets=
no_resolv_myname=0
no_tls1_2=
certfile=
extracas=
ssl_redirect=1
no_testing_cookie=1
host=my.domain.com
webprefixnoredir=0
relative_redir=0
redirect_port=443
redirect_host=my.domain.com
preroot_myusername=authentic-theme
webprefix=/webmin
trust_real_ip=1
noshowstderr=
nolistdir=
gzip=
expires_paths=
libwrap=
alwaysresolve=0
allow=10.0.0.0/24
utmp=
pam_end=
blocklock=
blockuser_failures=
blockuser_time=
session=0
session_ip=
no_pam=0
pam_conv=
logouttime=
`

my treafik_rules.yaml - I removed all routers, middlewares and services except for the ones relevant to webmin - all of them work except for webmin

`
# http protocol settings
http:

  # http routers

  routers:
    to-webmin:
      entryPoints:
      - "web"
      - "web-secure"
      rule: Host(`my.domain.com`)
      service: webmin
      middlewares:
      - httptohttps
#      - webminhttpsurl # tried with this middleware, failed - see comments on the middleware entry for details
      tls:
        certResolver: letsencrypt

# http middlewares

  middlewares:

# using the below to redirect http calls to https so that my authentication isn't sent in plain text - ssl disabled on webmin
# as traefik is handling TLS authentication
    httptohttps:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443

# using the below to add /webmin prefix to the my.domain.com url so it's my.domain.com/webmin otherwise it fails to load UI
    webmin:
      addPrefix:
        prefix: "/webmin"

#  tried with the below to replace http with https, failed so disabled this (it also caused all my other services to become 404)
#    webminhttpsurl:
#      redirectRegex:
#        regex: "^(.*)(:443)"
#        replacement: "https:\/\/${1}"
#        permanent: true

  # http services
  services:

    webmin:
      loadBalancer:
        servers:
        - url: "http://10.0.0.100:10000"
        passHostHeader: true  #tried with false - same failure

`

**Comment by user897943** [comment]
Correction for one of the points above:
On IP access control, I told webmin to only accept connections from 10.0.0.0/24 - my traefik server is on the same subnet

I was using a VPN so it was letting me in, because the VPN made it seem like I was on the local subnet. When I disabled the subnet, it blocked my public external IPv4 address, so I had to change the option to accept all addresses.

My concern with the hack above is, if webmin was updated and removed the http authentication anyone with my admin url could get in.

**Comment by iliarostovtsev** [comment]
If you downgrade the package to Webmin 1.942 for testing purposes - does it work then any differently, if so, how exactly?

You can easily downgrade running the following command:

~~~
apt-get install --reinstall webmin=1.942
~~~

**Comment by user897943** [comment]
Before I do that, are you saying I can re-enable session authentication? Because on the main, that and disabling SSL is what the hack is about. I don't want to mess with my configuration before knowing what you would like me to do first because right now even though it's a hack at least it works... just insecurely. After you tell me what you'd like me to do, then I'll downgrade and let you know. If you just want me to downgrade and test as it is, then I don't see what difference it will make...

**Comment by iliarostovtsev** [comment]
> I don't want to mess with my configuration before knowing what you would like me to do first because right now even though it's a hack at least it works

Keep it then, if you not sure what to do.

> My concern with the hack above is, if webmin was updated and removed the http authentication anyone with my admin url could get in.

I don't think we ever remove this feature the way, so anyone could just login. :slightly_smiling_face:

**Comment by user897943** [comment]
Ok but this is what I said above, you guys don't want to fix it.... if so please just make that clear so we don't have to waste our time going through days of trial and error as that's exactly what I had to do. I appreciate that you guys do this for free by the way, I really do, and thanks, however this is a tool that gives access to really important parts of a server, and 2 factor authentication is extremely important as a barrier, so not only I and all other users behind reverse proxies have lost this functionality, we now have an unsecure plain text http connection. Really!? Is that the reputation you guys want to have!? Sorry but I'm sure you guys can do better - and yes, I would if I could, but I won't learn code overnight and develop the capability to code something like this by the end of the week... please state the limitations of your product and what you guys are willing and not willing to do but I don't find it acceptable to maintain such an insecure config, it is a horrible hack and I would keep it for a short period while a solution was found but I certainly don't feel it's right to tell your users to just disable important security measures permanently. I hope you take the comment the way it's intended, it's not personal.

**Comment by iliarostovtsev** [comment]
> What I said above, you guys don't want to fix it.... if so please just make that clear so we don't have to waste our time going through days of trial and error as that's exactly what I had to do

We fixed that and all others seemed to be able to configure it and were happy about it. There are plenty of people [here](https://github.com/webmin/webmin/issues/1135) who uses Traefik, go ahead and ask them first, if they experience the same issue.

> .. we now have an unsecure plain text http connection

Assuming that you're running Traefik and Webmin on the same server it is _not that_ insecure, in case initial connection between you and your proxy is in SSL.

> I appreciate that you guys do this for free by the way, I really do, and thanks

Most of the time, we don't feel that, unfortunately.

>  Really!? Is that the reputation you guys want to have!? Sorry but I'm sure you guys can do better - and yes, I would if I could, but I won't learn code overnight

I wonder what would you say if you mis-configuring something?

> Sorry but I'm sure you guys can do better - and yes, I would if I could

While you could, we have to.

> Please state the limitations of your product and what you guys are willing and not willing to do but I don't find it acceptable to maintain such an insecure config

Why does it work perfectly fine with Apache proxy?

> It is a horrible hack and I would keep it for a short period while a solution was found 

Think why this is happening in one type of auth and doesn't in the other, and share your ideas.

> I hope you take the comment the way it's intended, it's not personal.

We don't take it personal, it's just personalities who work and support it in the end, no matter what.

**Comment by user897943** [comment]
Apologies if you guys feel that I'm not thankful, I definitely am, and I know that there has been a ton of work to make what you already have to offer, it's just that for me, it's not working.

Please trust me on this, I have searched the web extensively even trying to find an appropriate Regex rule for traefik, it simply does not work. It seems to be some sort of cookie issue. I have actually read all the threads that you have linked including on your last post and I have tried several different combinations which have not worked. The only way it works for me is disabling authentication but that disables 2 factor and I do not want that...


Traefik is doing TLS encryption with LetsEncrypt certificate of course, but I would like to use 2 factor for enhanced level of security since Webmin allows so many low level system changes that can really compromise my personal data. I run all possible services locally in my own server just to keep it all away from advertisers and who knows who... I really like Webmin, I just wish it works for me behind traefik. I do not think I have misconfigured it.

If you could offer further suggestions I would appreciate it a lot. I do not think I'm the only guy having issues, sometimes people prefer to try another solution rather than going through this, but I want to use Webmin and try to help you help me and others rather than using something else. I don't demand anything from you or anybody, after all it is your personal time, I just wanted to know, are you willing to please help me, if not that's fine just tell me and I'll try to find a different solution that is more secure. Thanks

**Comment by wiserweb** [comment]
@user897943 2FA is false security! If someone wants to get into your system they can pay $50 to a cell phone agent and have your telephone number ported to another provider. The attacker can then get the 2FA code and enter into the system.

In other words, 2FA is only as secure as the service provider. See the recent Telus/Koodoo leak that occured in Canada where someone was able to get access to a copy of their customer database via a trusted third party. All the security in the world won't do a damn thing if your have a weak link in the chain.

Good luck with your 'security'.

**Comment by user897943** [comment]
@wiserweb well you have just exposed your ignorance, webmin uses authenticator apps not SMS for 2 factor, it's very safe. I won't be interacting with you further, if you're not even aware of basic security features I don't understand why you'd get involved. Please desist from spending time to be unproductive, you're doing everyone a disservice.

**Comment by wiserweb** [comment]
@user897943  Every once is a while there's a special person that comments exactly your style... they're the worst people and I come out especially to slap them in the face. Are you a Brit? American? Where are you and who are you?

**Comment by user897943** [comment]
> @user897943 Every once in a while there's a special person that comments exactly your style... they're the worst people and I come out especially to slap them in the face. Are you a Brit? American? Where are you and who are you?

![Annotation 2020-07-20 192206](https://user-images.githubusercontent.com/5891221/87972261-85773300-cabe-11ea-80d6-0aaa09ccc4b5.png)

Waste your time :-)

**Comment by wiserweb** [comment]
Have a good rest of day.

**Comment by user897943** [comment]
I am here to apologize for coming here and "offending" the webmin developers by asking how to make it work behind a popular reverse proxy when all of the other services I have on my network (11 services) work without a problem. I am very sorry for daring to ask for help to maintain a secure environment through 2 factor authentication offered by webmin itself. I loved the response above saying that 2FA is not secure. I am however very please to say that I have solved this issue!!!!!!

For anyone who's using webmin behind traefik and you want to retain security, you only need to SSH into your server where webmin is installed, and execute the following command, which will uninstall webmin completely and allow you to have a secure server, because any developer of any application who does not take security seriously should not be releasing applications that make changes as root, and to expect their users to hack things and leave the service insecure is a joke.

/etc/webmin/uninstall.sh 

This issue has been going on for a long time and rather than listen and cooperate to fix the issue for once, I was just pointed to some threads saying "this has been fixed a long time ago". Clearly not. I spent two days trying all sorts of different configs as suggested and nothing has worked except disabling authentication which is absolutely horrendous and exposes my system completely. Let me just pose this one question here: If the developers cannot find a way to make security/authentication work behind a simple, well known reverse proxy like Traefik, do you trust them to make changes as root? If they cannot figure that out, some hacker will know how to bypass the "security".

Do yourself a favor and uninstall webmin, no matter what the developer says you are better off without it, if something bad happens do you think the developer will go and fix it for you? Keep dreaming... run the uninstall command and never worry again. You're welcome.

**Comment by iliarostovtsev** [comment]
> Do yourself a favor and uninstall Webmin, no matter what the developer says you are better off without it, if something bad happens do you think the developer will go and fix it for you? Keep dreaming... run the uninstall command and never worry again. You're welcome.

We will consider that you are simply **_spamming_**. Any software considered to be secure until proven otherwise!

The fact that you cannot configure services correctly doesn't make them insecure.

We are always taking security issues seriously and patch any found proof issues urgently. If you believe there is a security issue,  email us privately to _security@_ email address, with steps to reproduce an issue, and we will surely be able to fix that as soon as possible or/and even be able to reward your efforts!

**Comment by iliaross** [comment]
For anyone having issues with Cloudflare Tunnel and Webmin, check out this post that explains what needs to be done:

https://forum.virtualmin.com/t/webmin-2fa-cloudflare-tunnel-ii-after-the-new-update-2-402/133989/5?u=ilia
